INSERT INTO categories (category_name) VALUES ('Humanities and Social Sciences');
INSERT INTO categories (category_name) VALUES ('STEM');
INSERT INTO categories (category_name) VALUES ('Art, Music, & Performance');
INSERT INTO categories (category_name) VALUES ('Business & Entrepreneurship');
INSERT INTO categories (category_name) VALUES ('Community Service & Volunteerism');
INSERT INTO categories (category_name) VALUES ('Greek Life, Fraternities, & Sororities');
INSERT INTO categories (category_name) VALUES ('Cultural and International');
INSERT INTO categories (category_name) VALUES ('University Programs');
INSERT INTO categories (category_name) VALUES ('Environmental');
INSERT INTO categories (category_name) VALUES ('Governing Body');
INSERT INTO categories (category_name) VALUES ('Government & Politics');
INSERT INTO categories (category_name) VALUES ('Graduate and Professional Studies');
INSERT INTO categories (category_name) VALUES ('Honor Society');
INSERT INTO categories (category_name) VALUES ('Law & Law School');
INSERT INTO categories (category_name) VALUES ('Recreation & Wellness');
INSERT INTO categories (category_name) VALUES ('Religion & Spirituality');
INSERT INTO categories (category_name) VALUES ('Residence Life');
INSERT INTO categories (category_name) VALUES ('Social');
INSERT INTO categories (category_name) VALUES ('Social Justice, Advocacy & Activism');
