INSERT INTO clubs (club_name, members) VALUES ('Adobe Creative Club', 3);
INSERT INTO clubs_categories (club_id, category_id) VALUES (1, 3);
INSERT INTO clubs (club_name, members) VALUES ('Amuse Creative Writing Club', 104);
INSERT INTO clubs_categories (club_id, category_id) VALUES (2, 3);
INSERT INTO clubs (club_name, members) VALUES ('Buffoons', 14);
INSERT INTO clubs_categories (club_id, category_id) VALUES (3, 3);
INSERT INTO clubs (club_name, members) VALUES ('Circuit Benders', 14);
INSERT INTO clubs_categories (club_id, category_id) VALUES (4, 3);
INSERT INTO clubs (club_name, members) VALUES ('Colorado Bhangra Team', 12);
INSERT INTO clubs_categories (club_id, category_id) VALUES (5, 3);
INSERT INTO clubs (club_name, members) VALUES ('Crave the Sound', 28);
INSERT INTO clubs_categories (club_id, category_id) VALUES (6, 3);
INSERT INTO clubs (club_name, members) VALUES ('Creo', 3);
INSERT INTO clubs_categories (club_id, category_id) VALUES (7, 3);
INSERT INTO clubs (club_name, members) VALUES ('CU Abhinaya', 3);
INSERT INTO clubs_categories (club_id, category_id) VALUES (8, 3);
INSERT INTO clubs (club_name, members) VALUES ('CU American String Teachers Association', 1);
INSERT INTO clubs_categories (club_id, category_id) VALUES (9, 3);
INSERT INTO clubs (club_name, members) VALUES ('CU Boulder Collegiate Chapter of MTNA', 14);
INSERT INTO clubs_categories (club_id, category_id) VALUES (10, 3);
INSERT INTO clubs (club_name, members) VALUES ('CU Boulder Comedy Club', 12);
INSERT INTO clubs_categories (club_id, category_id) VALUES (11, 3);
INSERT INTO clubs (club_name, members) VALUES ('CU Boulder Cosplay Club', 5);
INSERT INTO clubs_categories (club_id, category_id) VALUES (12, 3);
INSERT INTO clubs (club_name, members) VALUES ('CU Breaking Club', 12);
INSERT INTO clubs_categories (club_id, category_id) VALUES (13, 3);
INSERT INTO clubs (club_name, members) VALUES ('CU Burlesque', 58);
INSERT INTO clubs_categories (club_id, category_id) VALUES (14, 3);
INSERT INTO clubs (club_name, members) VALUES ('CU Ceramics Club', 98);
INSERT INTO clubs_categories (club_id, category_id) VALUES (15, 3);
INSERT INTO clubs (club_name, members) VALUES ('CU Game Development and Graphics Club', 23);
INSERT INTO clubs_categories (club_id, category_id) VALUES (16, 3);
INSERT INTO clubs (club_name, members) VALUES ('CU Independent', 2);
INSERT INTO clubs_categories (club_id, category_id) VALUES (17, 3);
INSERT INTO clubs (club_name, members) VALUES ('CU Jam Society', 42);
INSERT INTO clubs_categories (club_id, category_id) VALUES (18, 3);
INSERT INTO clubs (club_name, members) VALUES ('CU On The Rocks', 9);
INSERT INTO clubs_categories (club_id, category_id) VALUES (19, 3);
INSERT INTO clubs (club_name, members) VALUES ('CU Rave Club', 141);
INSERT INTO clubs_categories (club_id, category_id) VALUES (20, 3);
INSERT INTO clubs (club_name, members) VALUES ('Delta Rho Chapter of Mu Phi Epsilon', 2);
INSERT INTO clubs_categories (club_id, category_id) VALUES (21, 3);
INSERT INTO clubs (club_name, members) VALUES ('Earth Muffins', 4);
INSERT INTO clubs_categories (club_id, category_id) VALUES (22, 3);
INSERT INTO clubs (club_name, members) VALUES ('Elevation', 5);
INSERT INTO clubs_categories (club_id, category_id) VALUES (23, 3);
INSERT INTO clubs (club_name, members) VALUES ('Emergency Painting', 6);
INSERT INTO clubs_categories (club_id, category_id) VALUES (24, 3);
INSERT INTO clubs (club_name, members) VALUES ('enACTs', 2);
INSERT INTO clubs_categories (club_id, category_id) VALUES (25, 3);
INSERT INTO clubs (club_name, members) VALUES ('Extreme Measures A Cappella', 8);
INSERT INTO clubs_categories (club_id, category_id) VALUES (26, 3);
INSERT INTO clubs (club_name, members) VALUES ('Graduate Musicology Society', 21);
INSERT INTO clubs_categories (club_id, category_id) VALUES (27, 3);
INSERT INTO clubs (club_name, members) VALUES ('Grand Canonical Ensemble', 10);
INSERT INTO clubs_categories (club_id, category_id) VALUES (28, 3);
INSERT INTO clubs (club_name, members) VALUES ('In The Buff A Cappella', 11);
INSERT INTO clubs_categories (club_id, category_id) VALUES (29, 3);
INSERT INTO clubs (club_name, members) VALUES ('Left Right Tim Improv Comedy', 4);
INSERT INTO clubs_categories (club_id, category_id) VALUES (30, 3);
INSERT INTO clubs (club_name, members) VALUES ('Marvel Super Movie Club', 52);
INSERT INTO clubs_categories (club_id, category_id) VALUES (31, 3);
INSERT INTO clubs (club_name, members) VALUES ('Meridian Creative Arts Journal', 11);
INSERT INTO clubs_categories (club_id, category_id) VALUES (32, 3);
INSERT INTO clubs (club_name, members) VALUES ('Mile 21 A cappella', 4);
INSERT INTO clubs_categories (club_id, category_id) VALUES (33, 3);
INSERT INTO clubs (club_name, members) VALUES ('Music Production Club', 24);
INSERT INTO clubs_categories (club_id, category_id) VALUES (34, 3);
INSERT INTO clubs (club_name, members) VALUES ('National Association for Music Education', 4);
INSERT INTO clubs_categories (club_id, category_id) VALUES (35, 3);
INSERT INTO clubs (club_name, members) VALUES ('On That Note', 2);
INSERT INTO clubs_categories (club_id, category_id) VALUES (36, 3);
INSERT INTO clubs (club_name, members) VALUES ('One Note Stand A cappella', 10);
INSERT INTO clubs_categories (club_id, category_id) VALUES (37, 3);
INSERT INTO clubs (club_name, members) VALUES ('Painting Pals', 94);
INSERT INTO clubs_categories (club_id, category_id) VALUES (38, 3);
INSERT INTO clubs (club_name, members) VALUES ('Photography Club', 95);
INSERT INTO clubs_categories (club_id, category_id) VALUES (39, 3);
INSERT INTO clubs (club_name, members) VALUES ('Sea U', 4);
INSERT INTO clubs_categories (club_id, category_id) VALUES (40, 3);
INSERT INTO clubs (club_name, members) VALUES ('Shuffle/Flow', 3);
INSERT INTO clubs_categories (club_id, category_id) VALUES (41, 3);
INSERT INTO clubs (club_name, members) VALUES ('Songwriting Club', 8);
INSERT INTO clubs_categories (club_id, category_id) VALUES (42, 3);
INSERT INTO clubs (club_name, members) VALUES ('Spaghetti Confession Improv', 5);
INSERT INTO clubs_categories (club_id, category_id) VALUES (43, 3);
INSERT INTO clubs (club_name, members) VALUES ('UCB Titan Productions', 56);
INSERT INTO clubs_categories (club_id, category_id) VALUES (44, 3);
INSERT INTO clubs (club_name, members) VALUES ('University of Colorado Trumpet Alliance', 22);
INSERT INTO clubs_categories (club_id, category_id) VALUES (45, 3);
INSERT INTO clubs (club_name, members) VALUES ('VeRVE Collisionz', 24);
INSERT INTO clubs_categories (club_id, category_id) VALUES (46, 3);
INSERT INTO clubs (club_name, members) VALUES ('Advertising Club', 101);
INSERT INTO clubs_categories (club_id, category_id) VALUES (47, 4);
INSERT INTO clubs (club_name, members) VALUES ('Alpha Kappa Psi', 10);
INSERT INTO clubs_categories (club_id, category_id) VALUES (48, 4);
INSERT INTO clubs (club_name, members) VALUES ('Association of Latino Professionals For America', 6);
INSERT INTO clubs_categories (club_id, category_id) VALUES (49, 4);
INSERT INTO clubs (club_name, members) VALUES ('B-Corp Club', 9);
INSERT INTO clubs_categories (club_id, category_id) VALUES (50, 4);
INSERT INTO clubs (club_name, members) VALUES ('Bitcoin Buffs', 10);
INSERT INTO clubs_categories (club_id, category_id) VALUES (51, 4);
INSERT INTO clubs (club_name, members) VALUES ('CannaBuffs', 133);
INSERT INTO clubs_categories (club_id, category_id) VALUES (52, 4);
INSERT INTO clubs (club_name, members) VALUES ('CESR Fellows', 7);
INSERT INTO clubs_categories (club_id, category_id) VALUES (53, 4);
INSERT INTO clubs (club_name, members) VALUES ('Colorado Credit Capital', 6);
INSERT INTO clubs_categories (club_id, category_id) VALUES (54, 4);
INSERT INTO clubs (club_name, members) VALUES ('Colorado Investment Management Society', 16);
INSERT INTO clubs_categories (club_id, category_id) VALUES (55, 4);
INSERT INTO clubs (club_name, members) VALUES ('CU American Marketing Association', 70);
INSERT INTO clubs_categories (club_id, category_id) VALUES (56, 4);
INSERT INTO clubs (club_name, members) VALUES ('CU Boulder Salesforce Student Group', 5);
INSERT INTO clubs_categories (club_id, category_id) VALUES (57, 4);
INSERT INTO clubs (club_name, members) VALUES ('CU Quants', 14);
INSERT INTO clubs_categories (club_id, category_id) VALUES (58, 4);
INSERT INTO clubs (club_name, members) VALUES ('CU Real Estate Club', 45);
INSERT INTO clubs_categories (club_id, category_id) VALUES (59, 4);
INSERT INTO clubs (club_name, members) VALUES ('CU Sports Career Group', 7);
INSERT INTO clubs_categories (club_id, category_id) VALUES (60, 4);
INSERT INTO clubs (club_name, members) VALUES ('Delta Sigma Pi', 8);
INSERT INTO clubs_categories (club_id, category_id) VALUES (61, 4);
INSERT INTO clubs (club_name, members) VALUES ('Evening MBA Association', 3);
INSERT INTO clubs_categories (club_id, category_id) VALUES (62, 4);
INSERT INTO clubs (club_name, members) VALUES ('Financial Planning Club', 12);
INSERT INTO clubs_categories (club_id, category_id) VALUES (63, 4);
INSERT INTO clubs (club_name, members) VALUES ('Leed's Net Impact', 1);
INSERT INTO clubs_categories (club_id, category_id) VALUES (64, 4);
INSERT INTO clubs (club_name, members) VALUES ('Leeds Association for Information Systems', 6);
INSERT INTO clubs_categories (club_id, category_id) VALUES (65, 4);
INSERT INTO clubs (club_name, members) VALUES ('Leeds Consulting Group', 17);
INSERT INTO clubs_categories (club_id, category_id) VALUES (66, 4);
INSERT INTO clubs (club_name, members) VALUES ('Leeds Investment and Trading Group', 116);
INSERT INTO clubs_categories (club_id, category_id) VALUES (67, 4);
INSERT INTO clubs (club_name, members) VALUES ('Leeds Outdoor Industry Club', 25);
INSERT INTO clubs_categories (club_id, category_id) VALUES (68, 4);
INSERT INTO clubs (club_name, members) VALUES ('Leeds Venture Club', 5);
INSERT INTO clubs_categories (club_id, category_id) VALUES (69, 4);
INSERT INTO clubs (club_name, members) VALUES ('Let's Talk Data', 1);
INSERT INTO clubs_categories (club_id, category_id) VALUES (70, 4);
INSERT INTO clubs (club_name, members) VALUES ('Music Industry Club', 37);
INSERT INTO clubs_categories (club_id, category_id) VALUES (71, 4);
INSERT INTO clubs (club_name, members) VALUES ('Scholars of Finance', 11);
INSERT INTO clubs_categories (club_id, category_id) VALUES (72, 4);
INSERT INTO clubs (club_name, members) VALUES ('The Adam Smith Society', 3);
INSERT INTO clubs_categories (club_id, category_id) VALUES (73, 4);
INSERT INTO clubs (club_name, members) VALUES ('Thunderchief Booster Club', 4);
INSERT INTO clubs_categories (club_id, category_id) VALUES (74, 4);
INSERT INTO clubs (club_name, members) VALUES ('Veteran's Business Club', 9);
INSERT INTO clubs_categories (club_id, category_id) VALUES (75, 4);
INSERT INTO clubs (club_name, members) VALUES ('Women in Business', 118);
INSERT INTO clubs_categories (club_id, category_id) VALUES (76, 4);
INSERT INTO clubs (club_name, members) VALUES ('Women in Economics', 2);
INSERT INTO clubs_categories (club_id, category_id) VALUES (77, 4);
INSERT INTO clubs (club_name, members) VALUES ('Women in Finance', 23);
INSERT INTO clubs_categories (club_id, category_id) VALUES (78, 4);
INSERT INTO clubs (club_name, members) VALUES ('Alpha Phi Omega - Gamma Theta', 5);
INSERT INTO clubs_categories (club_id, category_id) VALUES (79, 6);
INSERT INTO clubs (club_name, members) VALUES ('Arnold Air Society - Onizuka Squadron', 20);
INSERT INTO clubs_categories (club_id, category_id) VALUES (80, 6);
INSERT INTO clubs (club_name, members) VALUES ('Be the Match on Campus', 14);
INSERT INTO clubs_categories (club_id, category_id) VALUES (81, 6);
INSERT INTO clubs (club_name, members) VALUES ('Boulder Athletic Management Club', 5);
INSERT INTO clubs_categories (club_id, category_id) VALUES (82, 6);
INSERT INTO clubs (club_name, members) VALUES ('Circle K International', 17);
INSERT INTO clubs_categories (club_id, category_id) VALUES (83, 6);
INSERT INTO clubs (club_name, members) VALUES ('Collar Scholars', 295);
INSERT INTO clubs_categories (club_id, category_id) VALUES (84, 6);
INSERT INTO clubs (club_name, members) VALUES ('Colorado Homeless Assistance with Medicine Program', 27);
INSERT INTO clubs_categories (club_id, category_id) VALUES (85, 6);
INSERT INTO clubs (club_name, members) VALUES ('CU Rotaract Club', 14);
INSERT INTO clubs_categories (club_id, category_id) VALUES (86, 6);
INSERT INTO clubs (club_name, members) VALUES ('Engineers Without Borders', 113);
INSERT INTO clubs_categories (club_id, category_id) VALUES (87, 6);
INSERT INTO clubs (club_name, members) VALUES ('Generation Exchange', 3);
INSERT INTO clubs_categories (club_id, category_id) VALUES (88, 6);
INSERT INTO clubs (club_name, members) VALUES ('Global Dental Brigades', 5);
INSERT INTO clubs_categories (club_id, category_id) VALUES (89, 6);
INSERT INTO clubs (club_name, members) VALUES ('Global Medical Brigades', 17);
INSERT INTO clubs_categories (club_id, category_id) VALUES (90, 6);
INSERT INTO clubs (club_name, members) VALUES ('Kesem', 11);
INSERT INTO clubs_categories (club_id, category_id) VALUES (91, 6);
INSERT INTO clubs (club_name, members) VALUES ('Letters of Love CU-Boulder', 18);
INSERT INTO clubs_categories (club_id, category_id) VALUES (92, 6);
INSERT INTO clubs (club_name, members) VALUES ('National Residence Hall Honorary', 10);
INSERT INTO clubs_categories (club_id, category_id) VALUES (93, 6);
INSERT INTO clubs (club_name, members) VALUES ('Project Kind', 8);
INSERT INTO clubs_categories (club_id, category_id) VALUES (94, 6);
INSERT INTO clubs (club_name, members) VALUES ('Silver Wings', 1);
INSERT INTO clubs_categories (club_id, category_id) VALUES (95, 6);
INSERT INTO clubs (club_name, members) VALUES ('University of Colorado Emergency Medical Services', 31);
INSERT INTO clubs_categories (club_id, category_id) VALUES (96, 6);
INSERT INTO clubs (club_name, members) VALUES ('UNOS Ambassadors at CU', 16);
INSERT INTO clubs_categories (club_id, category_id) VALUES (97, 6);
INSERT INTO clubs (club_name, members) VALUES ('Volunteers Around the World CU Boulder Chapter', 8);
INSERT INTO clubs_categories (club_id, category_id) VALUES (98, 6);
INSERT INTO clubs (club_name, members) VALUES ('African Students Association', 27);
INSERT INTO clubs_categories (club_id, category_id) VALUES (99, 8);
INSERT INTO clubs (club_name, members) VALUES ('aiesec', 7);
INSERT INTO clubs_categories (club_id, category_id) VALUES (100, 8);
INSERT INTO clubs (club_name, members) VALUES ('Armenian Student Association', 5);
INSERT INTO clubs_categories (club_id, category_id) VALUES (101, 8);
INSERT INTO clubs (club_name, members) VALUES ('Asian American Literature Association', 5);
INSERT INTO clubs_categories (club_id, category_id) VALUES (102, 8);
INSERT INTO clubs (club_name, members) VALUES ('Asian Unity', 83);
INSERT INTO clubs_categories (club_id, category_id) VALUES (103, 8);
INSERT INTO clubs (club_name, members) VALUES ('Balkan Student Association', 3);
INSERT INTO clubs_categories (club_id, category_id) VALUES (104, 8);
INSERT INTO clubs (club_name, members) VALUES ('Boulder Bole Bhangra', 3);
INSERT INTO clubs_categories (club_id, category_id) VALUES (105, 8);
INSERT INTO clubs (club_name, members) VALUES ('Brazilian Student Association at the University of Colorado Boulder', 34);
INSERT INTO clubs_categories (club_id, category_id) VALUES (106, 8);
INSERT INTO clubs (club_name, members) VALUES ('Buffs4Israel', 8);
INSERT INTO clubs_categories (club_id, category_id) VALUES (107, 8);
INSERT INTO clubs (club_name, members) VALUES ('Chinese Students and Scholars Association', 23);
INSERT INTO clubs_categories (club_id, category_id) VALUES (108, 8);
INSERT INTO clubs (club_name, members) VALUES ('Cooking Through Cultures', 13);
INSERT INTO clubs_categories (club_id, category_id) VALUES (109, 8);
INSERT INTO clubs (club_name, members) VALUES ('CU Boulder Milana', 14);
INSERT INTO clubs_categories (club_id, category_id) VALUES (110, 8);
INSERT INTO clubs (club_name, members) VALUES ('CU Bridge Buffs', 12);
INSERT INTO clubs_categories (club_id, category_id) VALUES (111, 8);
INSERT INTO clubs (club_name, members) VALUES ('CU Catalan Club', 5);
INSERT INTO clubs_categories (club_id, category_id) VALUES (112, 8);
INSERT INTO clubs (club_name, members) VALUES ('CU International', 27);
INSERT INTO clubs_categories (club_id, category_id) VALUES (113, 8);
INSERT INTO clubs (club_name, members) VALUES ('Food For Thought', 8);
INSERT INTO clubs_categories (club_id, category_id) VALUES (114, 8);
INSERT INTO clubs (club_name, members) VALUES ('French Club', 29);
INSERT INTO clubs_categories (club_id, category_id) VALUES (115, 8);
INSERT INTO clubs (club_name, members) VALUES ('Friends of Doctors Without Borders at CU Boulder', 17);
INSERT INTO clubs_categories (club_id, category_id) VALUES (116, 8);
INSERT INTO clubs (club_name, members) VALUES ('Greek Club', 1);
INSERT INTO clubs_categories (club_id, category_id) VALUES (117, 8);
INSERT INTO clubs (club_name, members) VALUES ('Hindu YUVA', 11);
INSERT INTO clubs_categories (club_id, category_id) VALUES (118, 8);
INSERT INTO clubs (club_name, members) VALUES ('Indian Students Association', 103);
INSERT INTO clubs_categories (club_id, category_id) VALUES (119, 8);
INSERT INTO clubs (club_name, members) VALUES ('International Festival Committee', 10);
INSERT INTO clubs_categories (club_id, category_id) VALUES (120, 8);
INSERT INTO clubs (club_name, members) VALUES ('Japanese Student Association', 15);
INSERT INTO clubs_categories (club_id, category_id) VALUES (121, 8);
INSERT INTO clubs (club_name, members) VALUES ('Korean American Student Association', 2);
INSERT INTO clubs_categories (club_id, category_id) VALUES (122, 8);
INSERT INTO clubs (club_name, members) VALUES ('Korean Graduate Student Association', 24);
INSERT INTO clubs_categories (club_id, category_id) VALUES (123, 8);
INSERT INTO clubs (club_name, members) VALUES ('Kuwaiti Student Association', 4);
INSERT INTO clubs_categories (club_id, category_id) VALUES (124, 8);
INSERT INTO clubs (club_name, members) VALUES ('Native Graduate Student Group', 8);
INSERT INTO clubs_categories (club_id, category_id) VALUES (125, 8);
INSERT INTO clubs (club_name, members) VALUES ('Nepalese Student Association', 37);
INSERT INTO clubs_categories (club_id, category_id) VALUES (126, 8);
INSERT INTO clubs (club_name, members) VALUES ('Non-Traditional Student Organization', 10);
INSERT INTO clubs_categories (club_id, category_id) VALUES (127, 8);
INSERT INTO clubs (club_name, members) VALUES ('Oyate Native American and Indigenous Student Organization', 9);
INSERT INTO clubs_categories (club_id, category_id) VALUES (128, 8);
INSERT INTO clubs (club_name, members) VALUES ('Pakistani Student Association', 6);
INSERT INTO clubs_categories (club_id, category_id) VALUES (129, 8);
INSERT INTO clubs (club_name, members) VALUES ('Ritmos Latinos', 34);
INSERT INTO clubs_categories (club_id, category_id) VALUES (130, 8);
INSERT INTO clubs (club_name, members) VALUES ('Saudi Students Association at The University of Colorado at Boulder', 6);
INSERT INTO clubs_categories (club_id, category_id) VALUES (131, 8);
INSERT INTO clubs (club_name, members) VALUES ('Sikh Student Association', 0);
INSERT INTO clubs_categories (club_id, category_id) VALUES (132, 8);
INSERT INTO clubs (club_name, members) VALUES ('South Asian Student Association', 34);
INSERT INTO clubs_categories (club_id, category_id) VALUES (133, 8);
INSERT INTO clubs (club_name, members) VALUES ('Taiwanese Student Association at CU Boulder', 22);
INSERT INTO clubs_categories (club_id, category_id) VALUES (134, 8);
INSERT INTO clubs (club_name, members) VALUES ('Thai Student Association', 13);
INSERT INTO clubs_categories (club_id, category_id) VALUES (135, 8);
INSERT INTO clubs (club_name, members) VALUES ('The Tango Club', 12);
INSERT INTO clubs_categories (club_id, category_id) VALUES (136, 8);
INSERT INTO clubs (club_name, members) VALUES ('Vietnamese Student Association', 6);
INSERT INTO clubs_categories (club_id, category_id) VALUES (137, 8);
INSERT INTO clubs (club_name, members) VALUES ('American Conservation Coalition Boulder', 38);
INSERT INTO clubs_categories (club_id, category_id) VALUES (138, 10);
INSERT INTO clubs (club_name, members) VALUES ('Buffs Against Food Waste', 3);
INSERT INTO clubs_categories (club_id, category_id) VALUES (139, 10);
INSERT INTO clubs (club_name, members) VALUES ('Colorado Ocean Coalition', 59);
INSERT INTO clubs_categories (club_id, category_id) VALUES (140, 10);
INSERT INTO clubs (club_name, members) VALUES ('CU Boulder Chapter of the American Water Resources Association', 33);
INSERT INTO clubs_categories (club_id, category_id) VALUES (141, 10);
INSERT INTO clubs (club_name, members) VALUES ('CU Boulder Energy and Sustainability Society', 24);
INSERT INTO clubs_categories (club_id, category_id) VALUES (142, 10);
INSERT INTO clubs (club_name, members) VALUES ('CU Energy Club', 104);
INSERT INTO clubs_categories (club_id, category_id) VALUES (143, 10);
INSERT INTO clubs (club_name, members) VALUES ('CU Farm & Garden Club', 104);
INSERT INTO clubs_categories (club_id, category_id) VALUES (144, 10);
INSERT INTO clubs (club_name, members) VALUES ('CU Wildlife Club', 174);
INSERT INTO clubs_categories (club_id, category_id) VALUES (145, 10);
INSERT INTO clubs (club_name, members) VALUES ('EcoReps: Sustainability Leadership Program', 37);
INSERT INTO clubs_categories (club_id, category_id) VALUES (146, 10);
INSERT INTO clubs (club_name, members) VALUES ('Green Consulting Group', 4);
INSERT INTO clubs_categories (club_id, category_id) VALUES (147, 10);
INSERT INTO clubs (club_name, members) VALUES ('Industrial Design Society of America CU Boulder', 7);
INSERT INTO clubs_categories (club_id, category_id) VALUES (148, 10);
INSERT INTO clubs (club_name, members) VALUES ('Student Affiliate Chapter of the American Society of Landscape Architects at CU Boulder', 7);
INSERT INTO clubs_categories (club_id, category_id) VALUES (149, 10);
INSERT INTO clubs (club_name, members) VALUES ('The Society of Environmental Engineers', 26);
INSERT INTO clubs_categories (club_id, category_id) VALUES (150, 10);
INSERT INTO clubs (club_name, members) VALUES ('Arts and Sciences Student Government', 22);
INSERT INTO clubs_categories (club_id, category_id) VALUES (151, 11);
INSERT INTO clubs (club_name, members) VALUES ('CMCI Student Government', 22);
INSERT INTO clubs_categories (club_id, category_id) VALUES (152, 11);
INSERT INTO clubs (club_name, members) VALUES ('College of Music Student Government', 2);
INSERT INTO clubs_categories (club_id, category_id) VALUES (153, 11);
INSERT INTO clubs (club_name, members) VALUES ('CU Student Government', 54);
INSERT INTO clubs_categories (club_id, category_id) VALUES (154, 11);
INSERT INTO clubs (club_name, members) VALUES ('Environmental Design Student Government', 4);
INSERT INTO clubs_categories (club_id, category_id) VALUES (155, 11);
INSERT INTO clubs (club_name, members) VALUES ('Graduate and Professional Student Government', 8);
INSERT INTO clubs_categories (club_id, category_id) VALUES (156, 11);
INSERT INTO clubs (club_name, members) VALUES ('Interfraternity Council', 12);
INSERT INTO clubs_categories (club_id, category_id) VALUES (157, 11);
INSERT INTO clubs (club_name, members) VALUES ('Leeds Student Government', 13);
INSERT INTO clubs_categories (club_id, category_id) VALUES (158, 11);
INSERT INTO clubs (club_name, members) VALUES ('MBA Association', 1);
INSERT INTO clubs_categories (club_id, category_id) VALUES (159, 11);
INSERT INTO clubs (club_name, members) VALUES ('Panhellenic Council', 4);
INSERT INTO clubs_categories (club_id, category_id) VALUES (160, 11);
INSERT INTO clubs (club_name, members) VALUES ('Residence Hall Association', 15);
INSERT INTO clubs_categories (club_id, category_id) VALUES (161, 11);
INSERT INTO clubs (club_name, members) VALUES ('School of Education Student Government', 2);
INSERT INTO clubs_categories (club_id, category_id) VALUES (162, 11);
INSERT INTO clubs (club_name, members) VALUES ('Student Bar Association', 6);
INSERT INTO clubs_categories (club_id, category_id) VALUES (163, 11);
INSERT INTO clubs (club_name, members) VALUES ('Student Organizations Allocations Committee', 2);
INSERT INTO clubs_categories (club_id, category_id) VALUES (164, 11);
INSERT INTO clubs (club_name, members) VALUES ('University of Colorado Boulder Engineering Council', 11);
INSERT INTO clubs_categories (club_id, category_id) VALUES (165, 11);
INSERT INTO clubs (club_name, members) VALUES ('CU Boulder Democrats', 12);
INSERT INTO clubs_categories (club_id, category_id) VALUES (166, 12);
INSERT INTO clubs (club_name, members) VALUES ('CU Citizens' Climate Lobby', 28);
INSERT INTO clubs_categories (club_id, category_id) VALUES (167, 12);
INSERT INTO clubs (club_name, members) VALUES ('CU College Republicans', 36);
INSERT INTO clubs_categories (club_id, category_id) VALUES (168, 12);
INSERT INTO clubs (club_name, members) VALUES ('CU Political Science Club', 39);
INSERT INTO clubs_categories (club_id, category_id) VALUES (169, 12);
INSERT INTO clubs (club_name, members) VALUES ('Phi Alpha Delta Pre-Law Fraternity', 179);
INSERT INTO clubs_categories (club_id, category_id) VALUES (170, 12);
INSERT INTO clubs (club_name, members) VALUES ('Turning Point USA at the University of Colorado Boulder', 5);
INSERT INTO clubs_categories (club_id, category_id) VALUES (171, 12);
INSERT INTO clubs (club_name, members) VALUES ('Anthropology Graduate Student Association', 11);
INSERT INTO clubs_categories (club_id, category_id) VALUES (172, 13);
INSERT INTO clubs (club_name, members) VALUES ('ATOC Graduate Students', 16);
INSERT INTO clubs_categories (club_id, category_id) VALUES (173, 13);
INSERT INTO clubs (club_name, members) VALUES ('Black Graduate and Professional Student Association', 15);
INSERT INTO clubs_categories (club_id, category_id) VALUES (174, 13);
INSERT INTO clubs (club_name, members) VALUES ('CHEMunity', 6);
INSERT INTO clubs_categories (club_id, category_id) VALUES (175, 13);
INSERT INTO clubs (club_name, members) VALUES ('Computer Science Graduate Professional Development Club', 34);
INSERT INTO clubs_categories (club_id, category_id) VALUES (176, 13);
INSERT INTO clubs (club_name, members) VALUES ('CSI Test Organization', 1);
INSERT INTO clubs_categories (club_id, category_id) VALUES (177, 13);
INSERT INTO clubs (club_name, members) VALUES ('CU Boulder Asian Studies Graduate Association', 2);
INSERT INTO clubs_categories (club_id, category_id) VALUES (178, 13);
INSERT INTO clubs (club_name, members) VALUES ('CU Pre-Dental Society', 4);
INSERT INTO clubs_categories (club_id, category_id) VALUES (179, 13);
INSERT INTO clubs (club_name, members) VALUES ('CU Student Academy of Audiology', 17);
INSERT INTO clubs_categories (club_id, category_id) VALUES (180, 13);
INSERT INTO clubs (club_name, members) VALUES ('English Graduate Student Council', 3);
INSERT INTO clubs_categories (club_id, category_id) VALUES (181, 13);
INSERT INTO clubs (club_name, members) VALUES ('Geological Sciences Graduate Association', 12);
INSERT INTO clubs_categories (club_id, category_id) VALUES (182, 13);
INSERT INTO clubs (club_name, members) VALUES ('Information Science Graduate Student Association', 5);
INSERT INTO clubs_categories (club_id, category_id) VALUES (183, 13);
INSERT INTO clubs (club_name, members) VALUES ('National Student Speech Language Hearing Association', 5);
INSERT INTO clubs_categories (club_id, category_id) VALUES (184, 13);
INSERT INTO clubs (club_name, members) VALUES ('Beta Theta Pi', 13);
INSERT INTO clubs_categories (club_id, category_id) VALUES (185, 7);
INSERT INTO clubs (club_name, members) VALUES ('Colorado Delta Chi', 2);
INSERT INTO clubs_categories (club_id, category_id) VALUES (186, 7);
INSERT INTO clubs (club_name, members) VALUES ('Delta Sigma Phi', 20);
INSERT INTO clubs_categories (club_id, category_id) VALUES (187, 7);
INSERT INTO clubs (club_name, members) VALUES ('Delta Tau Delta', 5);
INSERT INTO clubs_categories (club_id, category_id) VALUES (188, 7);
INSERT INTO clubs (club_name, members) VALUES ('Delta Upsilon', 5);
INSERT INTO clubs_categories (club_id, category_id) VALUES (189, 7);
INSERT INTO clubs (club_name, members) VALUES ('Phi Delta Theta', 4);
INSERT INTO clubs_categories (club_id, category_id) VALUES (190, 7);
INSERT INTO clubs (club_name, members) VALUES ('Phi Kappa Sigma', 3);
INSERT INTO clubs_categories (club_id, category_id) VALUES (191, 7);
INSERT INTO clubs (club_name, members) VALUES ('Sigma Alpha Mu', 3);
INSERT INTO clubs_categories (club_id, category_id) VALUES (192, 7);
INSERT INTO clubs (club_name, members) VALUES ('Sigma Chi Fraternity', 3);
INSERT INTO clubs_categories (club_id, category_id) VALUES (193, 7);
INSERT INTO clubs (club_name, members) VALUES ('Sigma Tau Gamma', 0);
INSERT INTO clubs_categories (club_id, category_id) VALUES (194, 7);
INSERT INTO clubs (club_name, members) VALUES ('Emeralds of Kappa Delta Chi Sorority, Inc.', 12);
INSERT INTO clubs_categories (club_id, category_id) VALUES (195, 7);
INSERT INTO clubs (club_name, members) VALUES ('Multicultural Greek Council', 4);
INSERT INTO clubs_categories (club_id, category_id) VALUES (196, 7);
INSERT INTO clubs (club_name, members) VALUES ('Pi Delta Psi Fraternity Incorporated', 3);
INSERT INTO clubs_categories (club_id, category_id) VALUES (197, 7);
INSERT INTO clubs (club_name, members) VALUES ('Pi Lambda Chi Latina Sorority, Inc.', 5);
INSERT INTO clubs_categories (club_id, category_id) VALUES (198, 7);
INSERT INTO clubs (club_name, members) VALUES ('Sigma Lambda Beta International Fraternity Incorporated', 4);
INSERT INTO clubs_categories (club_id, category_id) VALUES (199, 7);
INSERT INTO clubs (club_name, members) VALUES ('Sigma Lambda Gamma National Sorority Inc.', 4);
INSERT INTO clubs_categories (club_id, category_id) VALUES (200, 7);
INSERT INTO clubs (club_name, members) VALUES ('Sigma Psi Zeta Sorority, Inc.', 7);
INSERT INTO clubs_categories (club_id, category_id) VALUES (201, 7);
INSERT INTO clubs (club_name, members) VALUES ('Tau Psi Omega Fraternity, Inc.', 7);
INSERT INTO clubs_categories (club_id, category_id) VALUES (202, 7);
INSERT INTO clubs (club_name, members) VALUES ('Theta Nu Xi, Multicultural Sorority, Inc.', 0);
INSERT INTO clubs_categories (club_id, category_id) VALUES (203, 7);
INSERT INTO clubs (club_name, members) VALUES ('Omega Psi Phi Fraternity, Inc', 1);
INSERT INTO clubs_categories (club_id, category_id) VALUES (204, 7);
INSERT INTO clubs (club_name, members) VALUES ('Alpha Chi Omega', 17);
INSERT INTO clubs_categories (club_id, category_id) VALUES (205, 7);
INSERT INTO clubs (club_name, members) VALUES ('Alpha Delta Chi', 4);
INSERT INTO clubs_categories (club_id, category_id) VALUES (206, 7);
INSERT INTO clubs (club_name, members) VALUES ('Alpha Phi', 7);
INSERT INTO clubs_categories (club_id, category_id) VALUES (207, 7);
INSERT INTO clubs (club_name, members) VALUES ('Chi Omega', 13);
INSERT INTO clubs_categories (club_id, category_id) VALUES (208, 7);
INSERT INTO clubs (club_name, members) VALUES ('Delta Delta Delta', 3);
INSERT INTO clubs_categories (club_id, category_id) VALUES (209, 7);
INSERT INTO clubs (club_name, members) VALUES ('Delta Gamma Sorority', 3);
INSERT INTO clubs_categories (club_id, category_id) VALUES (210, 7);
INSERT INTO clubs (club_name, members) VALUES ('Gamma Phi Beta', 2);
INSERT INTO clubs_categories (club_id, category_id) VALUES (211, 7);
INSERT INTO clubs (club_name, members) VALUES ('Kappa Alpha Theta, CU Boulder', 6);
INSERT INTO clubs_categories (club_id, category_id) VALUES (212, 7);
INSERT INTO clubs (club_name, members) VALUES ('Kappa Kappa Gamma', 2);
INSERT INTO clubs_categories (club_id, category_id) VALUES (213, 7);
INSERT INTO clubs (club_name, members) VALUES ('Phi Mu', 2);
INSERT INTO clubs_categories (club_id, category_id) VALUES (214, 7);
INSERT INTO clubs (club_name, members) VALUES ('Pi Beta Phi', 4);
INSERT INTO clubs_categories (club_id, category_id) VALUES (215, 7);
INSERT INTO clubs (club_name, members) VALUES ('Sigma Alpha Epsilon Pi', 4);
INSERT INTO clubs_categories (club_id, category_id) VALUES (216, 7);
INSERT INTO clubs (club_name, members) VALUES ('Alpha Epsilon Delta', 33);
INSERT INTO clubs_categories (club_id, category_id) VALUES (217, 14);
INSERT INTO clubs (club_name, members) VALUES ('National Society of Leadership and Success', 6);
INSERT INTO clubs_categories (club_id, category_id) VALUES (218, 14);
INSERT INTO clubs (club_name, members) VALUES ('National Society of Pershing Rifles Company B-9', 3);
INSERT INTO clubs_categories (club_id, category_id) VALUES (219, 14);
INSERT INTO clubs (club_name, members) VALUES ('Omega Chi Epsilon - Alpha Xi Chapter', 4);
INSERT INTO clubs_categories (club_id, category_id) VALUES (220, 14);
INSERT INTO clubs (club_name, members) VALUES ('Phi Sigma Pi - Delta Sigma Chapter', 6);
INSERT INTO clubs_categories (club_id, category_id) VALUES (221, 14);
INSERT INTO clubs (club_name, members) VALUES ('Pi Sigma Alpha', 3);
INSERT INTO clubs_categories (club_id, category_id) VALUES (222, 14);
INSERT INTO clubs (club_name, members) VALUES ('Psi Chi - CU Boulder Chapter', 47);
INSERT INTO clubs_categories (club_id, category_id) VALUES (223, 14);
INSERT INTO clubs (club_name, members) VALUES ('Sigma Gamma Tau', 5);
INSERT INTO clubs_categories (club_id, category_id) VALUES (224, 14);
INSERT INTO clubs (club_name, members) VALUES ('Tau Sigma National Honor Society for Transfer Students', 7);
INSERT INTO clubs_categories (club_id, category_id) VALUES (225, 14);
INSERT INTO clubs (club_name, members) VALUES ('The National Society of Collegiate Scholars', 20);
INSERT INTO clubs_categories (club_id, category_id) VALUES (226, 14);
INSERT INTO clubs (club_name, members) VALUES ('The National Society of Scabbard and Blade', 2);
INSERT INTO clubs_categories (club_id, category_id) VALUES (227, 14);
INSERT INTO clubs (club_name, members) VALUES ('American Planning Association for Students', 7);
INSERT INTO clubs_categories (club_id, category_id) VALUES (228, 1);
INSERT INTO clubs (club_name, members) VALUES ('Anthropology Club', 25);
INSERT INTO clubs_categories (club_id, category_id) VALUES (229, 1);
INSERT INTO clubs (club_name, members) VALUES ('Creative Nonfiction Club', 9);
INSERT INTO clubs_categories (club_id, category_id) VALUES (230, 1);
INSERT INTO clubs (club_name, members) VALUES ('CU Linguistics Club', 17);
INSERT INTO clubs_categories (club_id, category_id) VALUES (231, 1);
INSERT INTO clubs (club_name, members) VALUES ('CU Model United Nations', 24);
INSERT INTO clubs_categories (club_id, category_id) VALUES (232, 1);
INSERT INTO clubs (club_name, members) VALUES ('CU Psychology Club', 236);
INSERT INTO clubs_categories (club_id, category_id) VALUES (233, 1);
INSERT INTO clubs (club_name, members) VALUES ('CU Quiz Bowl', 8);
INSERT INTO clubs_categories (club_id, category_id) VALUES (234, 1);
INSERT INTO clubs (club_name, members) VALUES ('Culture, Language, and Social Practice Program (CLASP)', 5);
INSERT INTO clubs_categories (club_id, category_id) VALUES (235, 1);
INSERT INTO clubs (club_name, members) VALUES ('History Club', 45);
INSERT INTO clubs_categories (club_id, category_id) VALUES (236, 1);
INSERT INTO clubs (club_name, members) VALUES ('History Graduate Student Association', 2);
INSERT INTO clubs_categories (club_id, category_id) VALUES (237, 1);
INSERT INTO clubs (club_name, members) VALUES ('Honors Journal Editorial Board', 5);
INSERT INTO clubs_categories (club_id, category_id) VALUES (238, 1);
INSERT INTO clubs (club_name, members) VALUES ('Public Relations Student Society of America', 10);
INSERT INTO clubs_categories (club_id, category_id) VALUES (239, 1);
INSERT INTO clubs (club_name, members) VALUES ('Rocky Mountain Interdisciplinary History Conference', 2);
INSERT INTO clubs_categories (club_id, category_id) VALUES (240, 1);
INSERT INTO clubs (club_name, members) VALUES ('Sociology Club', 4);
INSERT INTO clubs_categories (club_id, category_id) VALUES (241, 1);
INSERT INTO clubs (club_name, members) VALUES ('Spanish and Portuguese Graduate Association', 2);
INSERT INTO clubs_categories (club_id, category_id) VALUES (242, 1);
INSERT INTO clubs (club_name, members) VALUES ('Speech and Debate Team at CU Boulder', 31);
INSERT INTO clubs_categories (club_id, category_id) VALUES (243, 1);
INSERT INTO clubs (club_name, members) VALUES ('TEDxCU', 39);
INSERT INTO clubs_categories (club_id, category_id) VALUES (244, 1);
INSERT INTO clubs (club_name, members) VALUES ('The Colorado Historian', 9);
INSERT INTO clubs_categories (club_id, category_id) VALUES (245, 1);
INSERT INTO clubs (club_name, members) VALUES ('The Rocky Mountain Philosophy Conference', 5);
INSERT INTO clubs_categories (club_id, category_id) VALUES (246, 1);
INSERT INTO clubs (club_name, members) VALUES ('Women in Philosophy', 13);
INSERT INTO clubs_categories (club_id, category_id) VALUES (247, 1);
INSERT INTO clubs (club_name, members) VALUES ('Arab Law Student Association', 3);
INSERT INTO clubs_categories (club_id, category_id) VALUES (248, 15);
INSERT INTO clubs (club_name, members) VALUES ('Asian Pacific American Law Students Association', 3);
INSERT INTO clubs_categories (club_id, category_id) VALUES (249, 15);
INSERT INTO clubs (club_name, members) VALUES ('Black Law Student Association', 6);
INSERT INTO clubs_categories (club_id, category_id) VALUES (250, 15);
INSERT INTO clubs (club_name, members) VALUES ('Breakthrough Student Group', 3);
INSERT INTO clubs_categories (club_id, category_id) VALUES (251, 15);
INSERT INTO clubs (club_name, members) VALUES ('Cannabis Law League', 5);
INSERT INTO clubs_categories (club_id, category_id) VALUES (252, 15);
INSERT INTO clubs (club_name, members) VALUES ('Class of 2025 Board', 7);
INSERT INTO clubs_categories (club_id, category_id) VALUES (253, 15);
INSERT INTO clubs (club_name, members) VALUES ('Colorado Disability Justice Alliance', 3);
INSERT INTO clubs_categories (club_id, category_id) VALUES (254, 15);
INSERT INTO clubs (club_name, members) VALUES ('Colorado Law Animal Legal Defense Fund', 3);
INSERT INTO clubs_categories (club_id, category_id) VALUES (255, 15);
INSERT INTO clubs (club_name, members) VALUES ('CU Law Class of 2023', 4);
INSERT INTO clubs_categories (club_id, category_id) VALUES (256, 15);
INSERT INTO clubs (club_name, members) VALUES ('CU Mock Trial', 39);
INSERT INTO clubs_categories (club_id, category_id) VALUES (257, 15);
INSERT INTO clubs (club_name, members) VALUES ('Environmental Law Society', 6);
INSERT INTO clubs_categories (club_id, category_id) VALUES (258, 15);
INSERT INTO clubs (club_name, members) VALUES ('Family and Juvenile Law Club', 3);
INSERT INTO clubs_categories (club_id, category_id) VALUES (259, 15);
INSERT INTO clubs (club_name, members) VALUES ('Federalist Society for Law and Public Policy Studies', 2);
INSERT INTO clubs_categories (club_id, category_id) VALUES (260, 15);
INSERT INTO clubs (club_name, members) VALUES ('Health Law Society', 6);
INSERT INTO clubs_categories (club_id, category_id) VALUES (261, 15);
INSERT INTO clubs (club_name, members) VALUES ('If/When/How: Lawyering For Reproductive Justice', 5);
INSERT INTO clubs_categories (club_id, category_id) VALUES (262, 15);
INSERT INTO clubs (club_name, members) VALUES ('Immigration Law and Policy Society', 3);
INSERT INTO clubs_categories (club_id, category_id) VALUES (263, 15);
INSERT INTO clubs (club_name, members) VALUES ('International Moot Court', 4);
INSERT INTO clubs_categories (club_id, category_id) VALUES (264, 15);
INSERT INTO clubs (club_name, members) VALUES ('Korey Wise Innocence Project Student Group', 1);
INSERT INTO clubs_categories (club_id, category_id) VALUES (265, 15);
INSERT INTO clubs (club_name, members) VALUES ('Latinx Law Student Association', 4);
INSERT INTO clubs_categories (club_id, category_id) VALUES (266, 15);
INSERT INTO clubs (club_name, members) VALUES ('National Lawyers Guild', 3);
INSERT INTO clubs_categories (club_id, category_id) VALUES (267, 15);
INSERT INTO clubs (club_name, members) VALUES ('Native American Law Students Association', 3);
INSERT INTO clubs_categories (club_id, category_id) VALUES (268, 15);
INSERT INTO clubs (club_name, members) VALUES ('OUTLaw', 5);
INSERT INTO clubs_categories (club_id, category_id) VALUES (269, 15);
INSERT INTO clubs (club_name, members) VALUES ('Pre-Law Student Society', 4);
INSERT INTO clubs_categories (club_id, category_id) VALUES (270, 15);
INSERT INTO clubs (club_name, members) VALUES ('Privacy Law Society', 2);
INSERT INTO clubs_categories (club_id, category_id) VALUES (271, 15);
INSERT INTO clubs (club_name, members) VALUES ('Public Interest Student Association', 4);
INSERT INTO clubs_categories (club_id, category_id) VALUES (272, 15);
INSERT INTO clubs (club_name, members) VALUES ('Silicon Flatirons Student Group', 3);
INSERT INTO clubs_categories (club_id, category_id) VALUES (273, 15);
INSERT INTO clubs (club_name, members) VALUES ('The Space Law Society', 2);
INSERT INTO clubs_categories (club_id, category_id) VALUES (274, 15);
INSERT INTO clubs (club_name, members) VALUES ('Women of Color Collective', 4);
INSERT INTO clubs_categories (club_id, category_id) VALUES (275, 15);
INSERT INTO clubs (club_name, members) VALUES ('Women's Law Caucus', 10);
INSERT INTO clubs_categories (club_id, category_id) VALUES (276, 15);
INSERT INTO clubs (club_name, members) VALUES ('Alpine Club at CU', 239);
INSERT INTO clubs_categories (club_id, category_id) VALUES (277, 17);
INSERT INTO clubs (club_name, members) VALUES ('Aqua Buffs', 14);
INSERT INTO clubs_categories (club_id, category_id) VALUES (278, 17);
INSERT INTO clubs (club_name, members) VALUES ('Backcountry Club at CU', 252);
INSERT INTO clubs_categories (club_id, category_id) VALUES (279, 17);
INSERT INTO clubs (club_name, members) VALUES ('Backcountry Squatters', 134);
INSERT INTO clubs_categories (club_id, category_id) VALUES (280, 17);
INSERT INTO clubs (club_name, members) VALUES ('Boulder Barefoot Walkers', 23);
INSERT INTO clubs_categories (club_id, category_id) VALUES (281, 17);
INSERT INTO clubs (club_name, members) VALUES ('Boulder Freeride', 507);
INSERT INTO clubs_categories (club_id, category_id) VALUES (282, 17);
INSERT INTO clubs (club_name, members) VALUES ('Boulder Lifting Club', 174);
INSERT INTO clubs_categories (club_id, category_id) VALUES (283, 17);
INSERT INTO clubs (club_name, members) VALUES ('Buff Axes', 30);
INSERT INTO clubs_categories (club_id, category_id) VALUES (284, 17);
INSERT INTO clubs (club_name, members) VALUES ('Buff Brain Gym', 6);
INSERT INTO clubs_categories (club_id, category_id) VALUES (285, 17);
INSERT INTO clubs (club_name, members) VALUES ('Buffalo Country Swing', 6);
INSERT INTO clubs_categories (club_id, category_id) VALUES (286, 17);
INSERT INTO clubs (club_name, members) VALUES ('Campus Reproductive Resources', 4);
INSERT INTO clubs_categories (club_id, category_id) VALUES (287, 17);
INSERT INTO clubs (club_name, members) VALUES ('Capoeira Club', 13);
INSERT INTO clubs_categories (club_id, category_id) VALUES (288, 17);
INSERT INTO clubs (club_name, members) VALUES ('Caving Club', 94);
INSERT INTO clubs_categories (club_id, category_id) VALUES (289, 17);
INSERT INTO clubs (club_name, members) VALUES ('CHAARG', 17);
INSERT INTO clubs_categories (club_id, category_id) VALUES (290, 17);
INSERT INTO clubs (club_name, members) VALUES ('Colorado Law Adventure Club', 6);
INSERT INTO clubs_categories (club_id, category_id) VALUES (291, 17);
INSERT INTO clubs (club_name, members) VALUES ('Colorado Ski Racing', 12);
INSERT INTO clubs_categories (club_id, category_id) VALUES (292, 17);
INSERT INTO clubs (club_name, members) VALUES ('CU Boulder Esports', 48);
INSERT INTO clubs_categories (club_id, category_id) VALUES (293, 17);
INSERT INTO clubs (club_name, members) VALUES ('CU Boulder Gymnastics Club', 9);
INSERT INTO clubs_categories (club_id, category_id) VALUES (294, 17);
INSERT INTO clubs (club_name, members) VALUES ('CU Boulder Ice Skating Club', 106);
INSERT INTO clubs_categories (club_id, category_id) VALUES (295, 17);
INSERT INTO clubs (club_name, members) VALUES ('CU Boulder Swing Dance', 44);
INSERT INTO clubs_categories (club_id, category_id) VALUES (296, 17);
INSERT INTO clubs (club_name, members) VALUES ('CU Bridge Club', 11);
INSERT INTO clubs_categories (club_id, category_id) VALUES (297, 17);
INSERT INTO clubs (club_name, members) VALUES ('CU Climbing Team', 23);
INSERT INTO clubs_categories (club_id, category_id) VALUES (298, 17);
INSERT INTO clubs (club_name, members) VALUES ('CU Club Golf', 13);
INSERT INTO clubs_categories (club_id, category_id) VALUES (299, 17);
INSERT INTO clubs (club_name, members) VALUES ('CU CRICKET', 20);
INSERT INTO clubs_categories (club_id, category_id) VALUES (300, 17);
INSERT INTO clubs (club_name, members) VALUES ('CU Dance Party', 1);
INSERT INTO clubs_categories (club_id, category_id) VALUES (301, 17);
INSERT INTO clubs (club_name, members) VALUES ('CU Disc Golf', 54);
INSERT INTO clubs_categories (club_id, category_id) VALUES (302, 17);
INSERT INTO clubs (club_name, members) VALUES ('CU ED Support Group', 3);
INSERT INTO clubs_categories (club_id, category_id) VALUES (303, 17);
INSERT INTO clubs (club_name, members) VALUES ('CU Equestrian Team', 17);
INSERT INTO clubs_categories (club_id, category_id) VALUES (304, 17);
INSERT INTO clubs (club_name, members) VALUES ('CU Gaelic Club', 6);
INSERT INTO clubs_categories (club_id, category_id) VALUES (305, 17);
INSERT INTO clubs (club_name, members) VALUES ('CU Gaming', 157);
INSERT INTO clubs_categories (club_id, category_id) VALUES (306, 17);
INSERT INTO clubs (club_name, members) VALUES ('CU Juggling Club', 12);
INSERT INTO clubs_categories (club_id, category_id) VALUES (307, 17);
INSERT INTO clubs (club_name, members) VALUES ('CU Mountain Biking', 4);
INSERT INTO clubs_categories (club_id, category_id) VALUES (308, 17);
INSERT INTO clubs (club_name, members) VALUES ('CU Poker Club', 63);
INSERT INTO clubs_categories (club_id, category_id) VALUES (309, 17);
INSERT INTO clubs (club_name, members) VALUES ('CU Powerlifting', 97);
INSERT INTO clubs_categories (club_id, category_id) VALUES (310, 17);
INSERT INTO clubs (club_name, members) VALUES ('CU Quadball', 15);
INSERT INTO clubs_categories (club_id, category_id) VALUES (311, 17);
INSERT INTO clubs (club_name, members) VALUES ('CU Racquetball', 1);
INSERT INTO clubs_categories (club_id, category_id) VALUES (312, 17);
INSERT INTO clubs (club_name, members) VALUES ('CU Sailing', 43);
INSERT INTO clubs_categories (club_id, category_id) VALUES (313, 17);
INSERT INTO clubs (club_name, members) VALUES ('CU Watermelon Club', 49);
INSERT INTO clubs_categories (club_id, category_id) VALUES (314, 17);
INSERT INTO clubs (club_name, members) VALUES ('CU Windsports Club', 8);
INSERT INTO clubs_categories (club_id, category_id) VALUES (315, 17);
INSERT INTO clubs (club_name, members) VALUES ('CU Wrestling Club', 22);
INSERT INTO clubs_categories (club_id, category_id) VALUES (316, 17);
INSERT INTO clubs (club_name, members) VALUES ('Hiking Club at CU Boulder', 293);
INSERT INTO clubs_categories (club_id, category_id) VALUES (317, 17);
INSERT INTO clubs (club_name, members) VALUES ('Historical European Martial Arts at CU', 16);
INSERT INTO clubs_categories (club_id, category_id) VALUES (318, 17);
INSERT INTO clubs (club_name, members) VALUES ('Kungfu Buff', 3);
INSERT INTO clubs_categories (club_id, category_id) VALUES (319, 17);
INSERT INTO clubs (club_name, members) VALUES ('Magic: The Gathering Club', 23);
INSERT INTO clubs_categories (club_id, category_id) VALUES (320, 17);
INSERT INTO clubs (club_name, members) VALUES ('Nutrition Buffs', 64);
INSERT INTO clubs_categories (club_id, category_id) VALUES (321, 17);
INSERT INTO clubs (club_name, members) VALUES ('Pickup Soccer Club', 27);
INSERT INTO clubs_categories (club_id, category_id) VALUES (322, 17);
INSERT INTO clubs (club_name, members) VALUES ('Rocky Mountain Rescue Group CU Boulder Student Chapter', 35);
INSERT INTO clubs_categories (club_id, category_id) VALUES (323, 17);
INSERT INTO clubs (club_name, members) VALUES ('Shooting Sports at the University of Colorado', 4);
INSERT INTO clubs_categories (club_id, category_id) VALUES (324, 17);
INSERT INTO clubs (club_name, members) VALUES ('SKY Campus Happiness @ CU Boulder', 14);
INSERT INTO clubs_categories (club_id, category_id) VALUES (325, 17);
INSERT INTO clubs (club_name, members) VALUES ('Sportsman Club', 7);
INSERT INTO clubs_categories (club_id, category_id) VALUES (326, 17);
INSERT INTO clubs (club_name, members) VALUES ('Table Tennis at CU', 55);
INSERT INTO clubs_categories (club_id, category_id) VALUES (327, 17);
INSERT INTO clubs (club_name, members) VALUES ('Tea Club', 36);
INSERT INTO clubs_categories (club_id, category_id) VALUES (328, 17);
INSERT INTO clubs (club_name, members) VALUES ('The Game of Squash Organization', 3);
INSERT INTO clubs_categories (club_id, category_id) VALUES (329, 17);
INSERT INTO clubs (club_name, members) VALUES ('Track and Field Athletic Club', 26);
INSERT INTO clubs_categories (club_id, category_id) VALUES (330, 17);
INSERT INTO clubs (club_name, members) VALUES ('University of Colorado Boulder Running Club', 86);
INSERT INTO clubs_categories (club_id, category_id) VALUES (331, 17);
INSERT INTO clubs (club_name, members) VALUES ('University of Colorado Eventing Team', 4);
INSERT INTO clubs_categories (club_id, category_id) VALUES (332, 17);
INSERT INTO clubs (club_name, members) VALUES ('Yoga for Creativity', 105);
INSERT INTO clubs_categories (club_id, category_id) VALUES (333, 17);
INSERT INTO clubs (club_name, members) VALUES ('CU Freeskiing Team', 94);
INSERT INTO clubs_categories (club_id, category_id) VALUES (334, 17);
INSERT INTO clubs (club_name, members) VALUES ('Women's Club Soccer', 20);
INSERT INTO clubs_categories (club_id, category_id) VALUES (335, 17);
INSERT INTO clubs (club_name, members) VALUES ('1825', 6);
INSERT INTO clubs_categories (club_id, category_id) VALUES (336, 18);
INSERT INTO clubs (club_name, members) VALUES ('Asian American InterVarsity', 10);
INSERT INTO clubs_categories (club_id, category_id) VALUES (337, 18);
INSERT INTO clubs (club_name, members) VALUES ('Bhakti Yoga Club', 71);
INSERT INTO clubs_categories (club_id, category_id) VALUES (338, 18);
INSERT INTO clubs (club_name, members) VALUES ('Black Christians at CU', 13);
INSERT INTO clubs_categories (club_id, category_id) VALUES (339, 18);
INSERT INTO clubs (club_name, members) VALUES ('Boulder Campus Ministry', 8);
INSERT INTO clubs_categories (club_id, category_id) VALUES (340, 18);
INSERT INTO clubs (club_name, members) VALUES ('Bridges International', 3);
INSERT INTO clubs_categories (club_id, category_id) VALUES (341, 18);
INSERT INTO clubs (club_name, members) VALUES ('Buffalo Catholic', 18);
INSERT INTO clubs_categories (club_id, category_id) VALUES (342, 18);
INSERT INTO clubs (club_name, members) VALUES ('Campus Crusade for Christ', 6);
INSERT INTO clubs_categories (club_id, category_id) VALUES (343, 18);
INSERT INTO clubs (club_name, members) VALUES ('Chi Alpha', 4);
INSERT INTO clubs_categories (club_id, category_id) VALUES (344, 18);
INSERT INTO clubs (club_name, members) VALUES ('Christian Buffalo Fellowship', 4);
INSERT INTO clubs_categories (club_id, category_id) VALUES (345, 18);
INSERT INTO clubs (club_name, members) VALUES ('Christian Challenge', 4);
INSERT INTO clubs_categories (club_id, category_id) VALUES (346, 18);
INSERT INTO clubs (club_name, members) VALUES ('Christian Legal Society', 4);
INSERT INTO clubs_categories (club_id, category_id) VALUES (347, 18);
INSERT INTO clubs (club_name, members) VALUES ('CU Boulder Hillel', 29);
INSERT INTO clubs_categories (club_id, category_id) VALUES (348, 18);
INSERT INTO clubs (club_name, members) VALUES ('Elohim Academy', 3);
INSERT INTO clubs_categories (club_id, category_id) VALUES (349, 18);
INSERT INTO clubs (club_name, members) VALUES ('FHL Chinese Christian Fellowship', 2);
INSERT INTO clubs_categories (club_id, category_id) VALUES (350, 18);
INSERT INTO clubs (club_name, members) VALUES ('InterVarsity Graduate Christian Fellowship', 7);
INSERT INTO clubs_categories (club_id, category_id) VALUES (351, 18);
INSERT INTO clubs (club_name, members) VALUES ('Jewish Student Association', 7);
INSERT INTO clubs_categories (club_id, category_id) VALUES (352, 18);
INSERT INTO clubs (club_name, members) VALUES ('Latter Day Saint Student Association', 1);
INSERT INTO clubs_categories (club_id, category_id) VALUES (353, 18);
INSERT INTO clubs (club_name, members) VALUES ('Lighthouse Christian Bible Study', 4);
INSERT INTO clubs_categories (club_id, category_id) VALUES (354, 18);
INSERT INTO clubs (club_name, members) VALUES ('Lutheran Campus Ministry', 8);
INSERT INTO clubs_categories (club_id, category_id) VALUES (355, 18);
INSERT INTO clubs (club_name, members) VALUES ('Muslim Student Association', 22);
INSERT INTO clubs_categories (club_id, category_id) VALUES (356, 18);
INSERT INTO clubs (club_name, members) VALUES ('Mystics: Tarot and Astrology', 74);
INSERT INTO clubs_categories (club_id, category_id) VALUES (357, 18);
INSERT INTO clubs (club_name, members) VALUES ('Navigators', 3);
INSERT INTO clubs_categories (club_id, category_id) VALUES (358, 18);
INSERT INTO clubs (club_name, members) VALUES ('Orthodox Christian Fellowship', 6);
INSERT INTO clubs_categories (club_id, category_id) VALUES (359, 18);
INSERT INTO clubs (club_name, members) VALUES ('SIT HAPPENS | CU MEDITATION & THE BUDDHIST PATH', 12);
INSERT INTO clubs_categories (club_id, category_id) VALUES (360, 18);
INSERT INTO clubs (club_name, members) VALUES ('Student Mobilization', 1);
INSERT INTO clubs_categories (club_id, category_id) VALUES (361, 18);
INSERT INTO clubs (club_name, members) VALUES ('The Annex', 4);
INSERT INTO clubs_categories (club_id, category_id) VALUES (362, 18);
INSERT INTO clubs (club_name, members) VALUES ('University Lutheran Chapel', 2);
INSERT INTO clubs_categories (club_id, category_id) VALUES (363, 18);
INSERT INTO clubs (club_name, members) VALUES ('Andrews Hall', 13);
INSERT INTO clubs_categories (club_id, category_id) VALUES (364, 19);
INSERT INTO clubs (club_name, members) VALUES ('Arnett Hall', 10);
INSERT INTO clubs_categories (club_id, category_id) VALUES (365, 19);
INSERT INTO clubs (club_name, members) VALUES ('Baker Community Council', 1);
INSERT INTO clubs_categories (club_id, category_id) VALUES (366, 19);
INSERT INTO clubs (club_name, members) VALUES ('Baker Hall', 16);
INSERT INTO clubs_categories (club_id, category_id) VALUES (367, 19);
INSERT INTO clubs (club_name, members) VALUES ('Bear Creek & Weber Hall', 17);
INSERT INTO clubs_categories (club_id, category_id) VALUES (368, 19);
INSERT INTO clubs (club_name, members) VALUES ('Bear Creek Community Council', 6);
INSERT INTO clubs_categories (club_id, category_id) VALUES (369, 19);
INSERT INTO clubs (club_name, members) VALUES ('Buckingham Hall', 11);
INSERT INTO clubs_categories (club_id, category_id) VALUES (370, 19);
INSERT INTO clubs (club_name, members) VALUES ('Cheyenne Arapaho Community Council', 4);
INSERT INTO clubs_categories (club_id, category_id) VALUES (371, 19);
INSERT INTO clubs (club_name, members) VALUES ('Cheyenne Arapaho Hall', 17);
INSERT INTO clubs_categories (club_id, category_id) VALUES (372, 19);
INSERT INTO clubs (club_name, members) VALUES ('Darley Community Council', 4);
INSERT INTO clubs_categories (club_id, category_id) VALUES (373, 19);
INSERT INTO clubs (club_name, members) VALUES ('Darley Towers', 17);
INSERT INTO clubs_categories (club_id, category_id) VALUES (374, 19);
INSERT INTO clubs (club_name, members) VALUES ('Design Your Path LLC', 2);
INSERT INTO clubs_categories (club_id, category_id) VALUES (375, 19);
INSERT INTO clubs (club_name, members) VALUES ('Farrand Community Council', 2);
INSERT INTO clubs_categories (club_id, category_id) VALUES (376, 19);
INSERT INTO clubs (club_name, members) VALUES ('Farrand Hall', 11);
INSERT INTO clubs_categories (club_id, category_id) VALUES (377, 19);
INSERT INTO clubs (club_name, members) VALUES ('Hallett Community Council', 3);
INSERT INTO clubs_categories (club_id, category_id) VALUES (378, 19);
INSERT INTO clubs (club_name, members) VALUES ('Hallett Hall', 18);
INSERT INTO clubs_categories (club_id, category_id) VALUES (379, 19);
INSERT INTO clubs (club_name, members) VALUES ('Kitt Central & Andrews Community Council', 6);
INSERT INTO clubs_categories (club_id, category_id) VALUES (380, 19);
INSERT INTO clubs (club_name, members) VALUES ('Kitt West & Arnett Community Council', 3);
INSERT INTO clubs_categories (club_id, category_id) VALUES (381, 19);
INSERT INTO clubs (club_name, members) VALUES ('Kittredge Central Hall', 7);
INSERT INTO clubs_categories (club_id, category_id) VALUES (382, 19);
INSERT INTO clubs (club_name, members) VALUES ('Kittredge West Hall', 10);
INSERT INTO clubs_categories (club_id, category_id) VALUES (383, 19);
INSERT INTO clubs (club_name, members) VALUES ('Libby Community Council', 23);
INSERT INTO clubs_categories (club_id, category_id) VALUES (384, 19);
INSERT INTO clubs (club_name, members) VALUES ('Libby Hall', 14);
INSERT INTO clubs_categories (club_id, category_id) VALUES (385, 19);
INSERT INTO clubs (club_name, members) VALUES ('Quad Community Council', 3);
INSERT INTO clubs_categories (club_id, category_id) VALUES (386, 19);
INSERT INTO clubs (club_name, members) VALUES ('Residence Life', 11);
INSERT INTO clubs_categories (club_id, category_id) VALUES (387, 19);
INSERT INTO clubs (club_name, members) VALUES ('Residential Quad (Aden, Brackett, Cockrell, Crosman)', 14);
INSERT INTO clubs_categories (club_id, category_id) VALUES (388, 19);
INSERT INTO clubs (club_name, members) VALUES ('Sewall Community Council', 5);
INSERT INTO clubs_categories (club_id, category_id) VALUES (389, 19);
INSERT INTO clubs (club_name, members) VALUES ('Sewall Hall', 11);
INSERT INTO clubs_categories (club_id, category_id) VALUES (390, 19);
INSERT INTO clubs (club_name, members) VALUES ('Smith & Buckingham Community Council', 4);
INSERT INTO clubs_categories (club_id, category_id) VALUES (391, 19);
INSERT INTO clubs (club_name, members) VALUES ('Smith Hall', 13);
INSERT INTO clubs_categories (club_id, category_id) VALUES (392, 19);
INSERT INTO clubs (club_name, members) VALUES ('Stearns Community Council', 2);
INSERT INTO clubs_categories (club_id, category_id) VALUES (393, 19);
INSERT INTO clubs (club_name, members) VALUES ('Stearns East & West', 15);
INSERT INTO clubs_categories (club_id, category_id) VALUES (394, 19);
INSERT INTO clubs (club_name, members) VALUES ('Willard & Reed Hall', 19);
INSERT INTO clubs_categories (club_id, category_id) VALUES (395, 19);
INSERT INTO clubs (club_name, members) VALUES ('Williams Village East', 21);
INSERT INTO clubs_categories (club_id, category_id) VALUES (396, 19);
INSERT INTO clubs (club_name, members) VALUES ('Williams Village East Community Council', 3);
INSERT INTO clubs_categories (club_id, category_id) VALUES (397, 19);
INSERT INTO clubs (club_name, members) VALUES ('Williams Village North', 12);
INSERT INTO clubs_categories (club_id, category_id) VALUES (398, 19);
INSERT INTO clubs (club_name, members) VALUES ('Williams Village North Community Council', 4);
INSERT INTO clubs_categories (club_id, category_id) VALUES (399, 19);
INSERT INTO clubs (club_name, members) VALUES ('American Sign Language Club', 111);
INSERT INTO clubs_categories (club_id, category_id) VALUES (400, 20);
INSERT INTO clubs (club_name, members) VALUES ('Association for Students with Disabilities', 17);
INSERT INTO clubs_categories (club_id, category_id) VALUES (401, 20);
INSERT INTO clubs (club_name, members) VALUES ('Best Buddies at CU', 89);
INSERT INTO clubs_categories (club_id, category_id) VALUES (402, 20);
INSERT INTO clubs (club_name, members) VALUES ('Boulder Film Buffs', 32);
INSERT INTO clubs_categories (club_id, category_id) VALUES (403, 20);
INSERT INTO clubs (club_name, members) VALUES ('Boulderite Chess Club', 130);
INSERT INTO clubs_categories (club_id, category_id) VALUES (404, 20);
INSERT INTO clubs (club_name, members) VALUES ('Buffs Going Bananas', 46);
INSERT INTO clubs_categories (club_id, category_id) VALUES (405, 20);
INSERT INTO clubs (club_name, members) VALUES ('Coffee Club', 70);
INSERT INTO clubs_categories (club_id, category_id) VALUES (406, 20);
INSERT INTO clubs (club_name, members) VALUES ('Colorado Evans Scholars', 5);
INSERT INTO clubs_categories (club_id, category_id) VALUES (407, 20);
INSERT INTO clubs (club_name, members) VALUES ('Crochet and Conversation', 136);
INSERT INTO clubs_categories (club_id, category_id) VALUES (408, 20);
INSERT INTO clubs (club_name, members) VALUES ('CU Anime Club', 74);
INSERT INTO clubs_categories (club_id, category_id) VALUES (409, 20);
INSERT INTO clubs (club_name, members) VALUES ('CU Board Game Club', 55);
INSERT INTO clubs_categories (club_id, category_id) VALUES (410, 20);
INSERT INTO clubs (club_name, members) VALUES ('CU Book Club', 73);
INSERT INTO clubs_categories (club_id, category_id) VALUES (411, 20);
INSERT INTO clubs (club_name, members) VALUES ('CU Boulder Railroad Club', 7);
INSERT INTO clubs_categories (club_id, category_id) VALUES (412, 20);
INSERT INTO clubs (club_name, members) VALUES ('CU Cornhole Club', 141);
INSERT INTO clubs_categories (club_id, category_id) VALUES (413, 20);
INSERT INTO clubs (club_name, members) VALUES ('CU Dungeons and Dragons', 103);
INSERT INTO clubs_categories (club_id, category_id) VALUES (414, 20);
INSERT INTO clubs (club_name, members) VALUES ('CU Kathak and Folk Dance Club', 1);
INSERT INTO clubs_categories (club_id, category_id) VALUES (415, 20);
INSERT INTO clubs (club_name, members) VALUES ('Drag Buffs', 25);
INSERT INTO clubs_categories (club_id, category_id) VALUES (416, 20);
INSERT INTO clubs (club_name, members) VALUES ('Euchre Club', 3);
INSERT INTO clubs_categories (club_id, category_id) VALUES (417, 20);
INSERT INTO clubs (club_name, members) VALUES ('Gender & Sexuality Alliance', 73);
INSERT INTO clubs_categories (club_id, category_id) VALUES (418, 20);
INSERT INTO clubs (club_name, members) VALUES ('Good Grief!', 14);
INSERT INTO clubs_categories (club_id, category_id) VALUES (419, 20);
INSERT INTO clubs (club_name, members) VALUES ('Honor Guard', 3);
INSERT INTO clubs_categories (club_id, category_id) VALUES (420, 20);
INSERT INTO clubs (club_name, members) VALUES ('Humans versus Zombies at CU Boulder', 1);
INSERT INTO clubs_categories (club_id, category_id) VALUES (421, 20);
INSERT INTO clubs (club_name, members) VALUES ('Iranian Students at CU Boulder', 3);
INSERT INTO clubs_categories (club_id, category_id) VALUES (422, 20);
INSERT INTO clubs (club_name, members) VALUES ('Laser Tag & Pancakes', 118);
INSERT INTO clubs_categories (club_id, category_id) VALUES (423, 20);
INSERT INTO clubs (club_name, members) VALUES ('Pokemon TCG Boulder', 13);
INSERT INTO clubs_categories (club_id, category_id) VALUES (424, 20);
INSERT INTO clubs (club_name, members) VALUES ('Pokemon VGC', 20);
INSERT INTO clubs_categories (club_id, category_id) VALUES (425, 20);
INSERT INTO clubs (club_name, members) VALUES ('Roam Boulder', 20);
INSERT INTO clubs_categories (club_id, category_id) VALUES (426, 20);
INSERT INTO clubs (club_name, members) VALUES ('Say What!?: CU Boulder Hearing Loss Association', 3);
INSERT INTO clubs_categories (club_id, category_id) VALUES (427, 20);
INSERT INTO clubs (club_name, members) VALUES ('Senior Class Council', 8);
INSERT INTO clubs_categories (club_id, category_id) VALUES (428, 20);
INSERT INTO clubs (club_name, members) VALUES ('Society of Physics Students', 27);
INSERT INTO clubs_categories (club_id, category_id) VALUES (429, 20);
INSERT INTO clubs (club_name, members) VALUES ('Student Veterans Association', 5);
INSERT INTO clubs_categories (club_id, category_id) VALUES (430, 20);
INSERT INTO clubs (club_name, members) VALUES ('Success Enabled Pilots', 8);
INSERT INTO clubs_categories (club_id, category_id) VALUES (431, 20);
INSERT INTO clubs (club_name, members) VALUES ('Super Smash Brothers CU', 9);
INSERT INTO clubs_categories (club_id, category_id) VALUES (432, 20);
INSERT INTO clubs (club_name, members) VALUES ('Survivor at CU Boulder', 19);
INSERT INTO clubs_categories (club_id, category_id) VALUES (433, 20);
INSERT INTO clubs (club_name, members) VALUES ('The Diabetes Link at CU', 5);
INSERT INTO clubs_categories (club_id, category_id) VALUES (434, 20);
INSERT INTO clubs (club_name, members) VALUES ('The Women's Network: CU Boulder', 10);
INSERT INTO clubs_categories (club_id, category_id) VALUES (435, 20);
INSERT INTO clubs (club_name, members) VALUES ('Thriving Buffs', 8);
INSERT INTO clubs_categories (club_id, category_id) VALUES (436, 20);
INSERT INTO clubs (club_name, members) VALUES ('Warhammer Buffs', 27);
INSERT INTO clubs_categories (club_id, category_id) VALUES (437, 20);
INSERT INTO clubs (club_name, members) VALUES ('Young Life College', 28);
INSERT INTO clubs_categories (club_id, category_id) VALUES (438, 20);
INSERT INTO clubs (club_name, members) VALUES ('Yu-Gi-Oh Club', 6);
INSERT INTO clubs_categories (club_id, category_id) VALUES (439, 20);
INSERT INTO clubs (club_name, members) VALUES ('4Ukraine', 5);
INSERT INTO clubs_categories (club_id, category_id) VALUES (440, 21);
INSERT INTO clubs (club_name, members) VALUES ('Bandana Project', 8);
INSERT INTO clubs_categories (club_id, category_id) VALUES (441, 21);
INSERT INTO clubs (club_name, members) VALUES ('Black Student Alliance', 102);
INSERT INTO clubs_categories (club_id, category_id) VALUES (442, 21);
INSERT INTO clubs (club_name, members) VALUES ('Buffs for Reproductive Rights', 73);
INSERT INTO clubs_categories (club_id, category_id) VALUES (443, 21);
INSERT INTO clubs (club_name, members) VALUES ('Committee for Equity in Mechanical Engineering', 3);
INSERT INTO clubs_categories (club_id, category_id) VALUES (444, 21);
INSERT INTO clubs (club_name, members) VALUES ('CU Boulder Marxists', 15);
INSERT INTO clubs_categories (club_id, category_id) VALUES (445, 21);
INSERT INTO clubs (club_name, members) VALUES ('Disability Advocacy Student Union', 11);
INSERT INTO clubs_categories (club_id, category_id) VALUES (446, 21);
INSERT INTO clubs (club_name, members) VALUES ('End Overdose at CU Boulder', 16);
INSERT INTO clubs_categories (club_id, category_id) VALUES (447, 21);
INSERT INTO clubs (club_name, members) VALUES ('Fossil Free CU', 5);
INSERT INTO clubs_categories (club_id, category_id) VALUES (448, 21);
INSERT INTO clubs (club_name, members) VALUES ('Health Equity and Applied Learning', 27);
INSERT INTO clubs_categories (club_id, category_id) VALUES (449, 21);
INSERT INTO clubs (club_name, members) VALUES ('International Aerospace Students Association', 5);
INSERT INTO clubs_categories (club_id, category_id) VALUES (450, 21);
INSERT INTO clubs (club_name, members) VALUES ('Leading Women of Tomorrow', 30);
INSERT INTO clubs_categories (club_id, category_id) VALUES (451, 21);
INSERT INTO clubs (club_name, members) VALUES ('MECHA', 5);
INSERT INTO clubs_categories (club_id, category_id) VALUES (452, 21);
INSERT INTO clubs (club_name, members) VALUES ('NAMI on Campus at CU Boulder', 6);
INSERT INTO clubs_categories (club_id, category_id) VALUES (453, 21);
INSERT INTO clubs (club_name, members) VALUES ('New Era Colorado', 7);
INSERT INTO clubs_categories (club_id, category_id) VALUES (454, 21);
INSERT INTO clubs (club_name, members) VALUES ('One Love', 6);
INSERT INTO clubs_categories (club_id, category_id) VALUES (455, 21);
INSERT INTO clubs (club_name, members) VALUES ('Psychologists Advocating for Systemic Training in Antiracism', 13);
INSERT INTO clubs_categories (club_id, category_id) VALUES (456, 21);
INSERT INTO clubs (club_name, members) VALUES ('Students Against Campus Sexual Assault', 8);
INSERT INTO clubs_categories (club_id, category_id) VALUES (457, 21);
INSERT INTO clubs (club_name, members) VALUES ('Students Against Unjust Imprisonment', 14);
INSERT INTO clubs_categories (club_id, category_id) VALUES (458, 21);
INSERT INTO clubs (club_name, members) VALUES ('Students for United Campus Workers Colorado', 3);
INSERT INTO clubs_categories (club_id, category_id) VALUES (459, 21);
INSERT INTO clubs (club_name, members) VALUES ('Swap', 3);
INSERT INTO clubs_categories (club_id, category_id) VALUES (460, 21);
INSERT INTO clubs (club_name, members) VALUES ('The Brazen Project', 2);
INSERT INTO clubs_categories (club_id, category_id) VALUES (461, 21);
INSERT INTO clubs (club_name, members) VALUES ('United Mexican American Students', 16);
INSERT INTO clubs_categories (club_id, category_id) VALUES (462, 21);
INSERT INTO clubs (club_name, members) VALUES ('Vegan Justice League', 9);
INSERT INTO clubs_categories (club_id, category_id) VALUES (463, 21);
INSERT INTO clubs (club_name, members) VALUES ('Young Democratic Socialists of America', 42);
INSERT INTO clubs_categories (club_id, category_id) VALUES (464, 21);
INSERT INTO clubs (club_name, members) VALUES ('Aerospace Medicine Student and Resident Organization', 20);
INSERT INTO clubs_categories (club_id, category_id) VALUES (465, 2);
INSERT INTO clubs (club_name, members) VALUES ('American Association of Engineers of Indian Origin - University of Colorado - Boulder', 6);
INSERT INTO clubs_categories (club_id, category_id) VALUES (466, 2);
INSERT INTO clubs (club_name, members) VALUES ('American Indian Science and Engineering Society', 6);
INSERT INTO clubs_categories (club_id, category_id) VALUES (467, 2);
INSERT INTO clubs (club_name, members) VALUES ('American Institute of Aeronautics and Astronautics - CU Boulder Branch', 54);
INSERT INTO clubs_categories (club_id, category_id) VALUES (468, 2);
INSERT INTO clubs (club_name, members) VALUES ('American Institute of Chemical Engineers (AIChE)', 32);
INSERT INTO clubs_categories (club_id, category_id) VALUES (469, 2);
INSERT INTO clubs (club_name, members) VALUES ('American Medical Student Association', 151);
INSERT INTO clubs_categories (club_id, category_id) VALUES (470, 2);
INSERT INTO clubs (club_name, members) VALUES ('American Medical Women's Association', 94);
INSERT INTO clubs_categories (club_id, category_id) VALUES (471, 2);
INSERT INTO clubs (club_name, members) VALUES ('American Meteorological Society Student Chapter', 10);
INSERT INTO clubs_categories (club_id, category_id) VALUES (472, 2);
INSERT INTO clubs (club_name, members) VALUES ('American Society for Engineering Management', 28);
INSERT INTO clubs_categories (club_id, category_id) VALUES (473, 2);
INSERT INTO clubs (club_name, members) VALUES ('American Society of Civil Engineers', 18);
INSERT INTO clubs_categories (club_id, category_id) VALUES (474, 2);
INSERT INTO clubs (club_name, members) VALUES ('American Society of Mechanical Engineers', 27);
INSERT INTO clubs_categories (club_id, category_id) VALUES (475, 2);
INSERT INTO clubs (club_name, members) VALUES ('Antimicrobial Resistance Mediation OutReach', 20);
INSERT INTO clubs_categories (club_id, category_id) VALUES (476, 2);
INSERT INTO clubs (club_name, members) VALUES ('Assembly Language Club', 7);
INSERT INTO clubs_categories (club_id, category_id) VALUES (477, 2);
INSERT INTO clubs (club_name, members) VALUES ('Biomedical Engineering Society', 35);
INSERT INTO clubs_categories (club_id, category_id) VALUES (478, 2);
INSERT INTO clubs (club_name, members) VALUES ('Blueprint Boulder', 16);
INSERT INTO clubs_categories (club_id, category_id) VALUES (479, 2);
INSERT INTO clubs (club_name, members) VALUES ('Chem and Biochem Club', 45);
INSERT INTO clubs_categories (club_id, category_id) VALUES (480, 2);
INSERT INTO clubs (club_name, members) VALUES ('Coding Buffs', 2);
INSERT INTO clubs_categories (club_id, category_id) VALUES (481, 2);
INSERT INTO clubs (club_name, members) VALUES ('Colorado Engineer Magazine', 2);
INSERT INTO clubs_categories (club_id, category_id) VALUES (482, 2);
INSERT INTO clubs (club_name, members) VALUES ('Colorado WASH Symposium', 5);
INSERT INTO clubs_categories (club_id, category_id) VALUES (483, 2);
INSERT INTO clubs (club_name, members) VALUES ('Competitive Programming and Career Building Club', 72);
INSERT INTO clubs_categories (club_id, category_id) VALUES (484, 2);
INSERT INTO clubs (club_name, members) VALUES ('Computer Science Graduate Student Association', 10);
INSERT INTO clubs_categories (club_id, category_id) VALUES (485, 2);
INSERT INTO clubs (club_name, members) VALUES ('CU Astronomy Club', 10);
INSERT INTO clubs_categories (club_id, category_id) VALUES (486, 2);
INSERT INTO clubs (club_name, members) VALUES ('CU BioStatistics and Public Health Club', 5);
INSERT INTO clubs_categories (club_id, category_id) VALUES (487, 2);
INSERT INTO clubs (club_name, members) VALUES ('CU Blockchain', 41);
INSERT INTO clubs_categories (club_id, category_id) VALUES (488, 2);
INSERT INTO clubs (club_name, members) VALUES ('CU Boulder iGem Team', 5);
INSERT INTO clubs_categories (club_id, category_id) VALUES (489, 2);
INSERT INTO clubs (club_name, members) VALUES ('CU Boulder Racing Team', 205);
INSERT INTO clubs_categories (club_id, category_id) VALUES (490, 2);
INSERT INTO clubs (club_name, members) VALUES ('CU Boulder RoboSub Team', 19);
INSERT INTO clubs_categories (club_id, category_id) VALUES (491, 2);
INSERT INTO clubs (club_name, members) VALUES ('CU Cyber Club', 13);
INSERT INTO clubs_categories (club_id, category_id) VALUES (492, 2);
INSERT INTO clubs (club_name, members) VALUES ('CU Engineering World Health', 6);
INSERT INTO clubs_categories (club_id, category_id) VALUES (493, 2);
INSERT INTO clubs (club_name, members) VALUES ('CU Hyperloop', 12);
INSERT INTO clubs_categories (club_id, category_id) VALUES (494, 2);
INSERT INTO clubs (club_name, members) VALUES ('CU Museum Club', 9);
INSERT INTO clubs_categories (club_id, category_id) VALUES (495, 2);
INSERT INTO clubs (club_name, members) VALUES ('CU Mycology Club', 89);
INSERT INTO clubs_categories (club_id, category_id) VALUES (496, 2);
INSERT INTO clubs (club_name, members) VALUES ('CU Physician Assistant Club', 22);
INSERT INTO clubs_categories (club_id, category_id) VALUES (497, 2);
INSERT INTO clubs (club_name, members) VALUES ('CU Physics Olympiad', 3);
INSERT INTO clubs_categories (club_id, category_id) VALUES (498, 2);
INSERT INTO clubs (club_name, members) VALUES ('CU Robotics', 64);
INSERT INTO clubs_categories (club_id, category_id) VALUES (499, 2);
INSERT INTO clubs (club_name, members) VALUES ('CU Rover Team', 29);
INSERT INTO clubs_categories (club_id, category_id) VALUES (500, 2);
INSERT INTO clubs (club_name, members) VALUES ('CU Social Psychology Lab', 21);
INSERT INTO clubs_categories (club_id, category_id) VALUES (501, 2);
INSERT INTO clubs (club_name, members) VALUES ('CU Sounding Rocket Laboratory', 165);
INSERT INTO clubs_categories (club_id, category_id) VALUES (502, 2);
INSERT INTO clubs (club_name, members) VALUES ('CU Student Chapter of the Society of American Military Engineers', 5);
INSERT INTO clubs_categories (club_id, category_id) VALUES (503, 2);
INSERT INTO clubs (club_name, members) VALUES ('CU Students for the Exploration and Development of Space', 14);
INSERT INTO clubs_categories (club_id, category_id) VALUES (504, 2);
INSERT INTO clubs (club_name, members) VALUES ('CU Technology for Extreme Environments', 8);
INSERT INTO clubs_categories (club_id, category_id) VALUES (505, 2);
INSERT INTO clubs (club_name, members) VALUES ('CU Wind Energy Club', 8);
INSERT INTO clubs_categories (club_id, category_id) VALUES (506, 2);
INSERT INTO clubs (club_name, members) VALUES ('CU Women in Computing', 28);
INSERT INTO clubs_categories (club_id, category_id) VALUES (507, 2);
INSERT INTO clubs (club_name, members) VALUES ('CU-Prime', 7);
INSERT INTO clubs_categories (club_id, category_id) VALUES (508, 2);
INSERT INTO clubs (club_name, members) VALUES ('Data Buffs', 35);
INSERT INTO clubs_categories (club_id, category_id) VALUES (509, 2);
INSERT INTO clubs (club_name, members) VALUES ('Data Science Student Association', 9);
INSERT INTO clubs_categories (club_id, category_id) VALUES (510, 2);
INSERT INTO clubs (club_name, members) VALUES ('Design Build Fly', 31);
INSERT INTO clubs_categories (club_id, category_id) VALUES (511, 2);
INSERT INTO clubs (club_name, members) VALUES ('Design for America', 4);
INSERT INTO clubs_categories (club_id, category_id) VALUES (512, 2);
INSERT INTO clubs (club_name, members) VALUES ('Earthquake Engineering Research Institute', 1);
INSERT INTO clubs_categories (club_id, category_id) VALUES (513, 2);
INSERT INTO clubs (club_name, members) VALUES ('Electrochemical Society at CU Boulder', 4);
INSERT INTO clubs_categories (club_id, category_id) VALUES (514, 2);
INSERT INTO clubs (club_name, members) VALUES ('FPV Society At CU Boulder', 6);
INSERT INTO clubs_categories (club_id, category_id) VALUES (515, 2);
INSERT INTO clubs (club_name, members) VALUES ('Global Surgery Student Alliance at CU Boulder', 5);
INSERT INTO clubs_categories (club_id, category_id) VALUES (516, 2);
INSERT INTO clubs (club_name, members) VALUES ('Google Developer Student Clubs University of Colorado Boulder', 3);
INSERT INTO clubs_categories (club_id, category_id) VALUES (517, 2);
INSERT INTO clubs (club_name, members) VALUES ('HackCU', 6);
INSERT INTO clubs_categories (club_id, category_id) VALUES (518, 2);
INSERT INTO clubs (club_name, members) VALUES ('HOSA - Future Health Professionals', 14);
INSERT INTO clubs_categories (club_id, category_id) VALUES (519, 2);
INSERT INTO clubs (club_name, members) VALUES ('Illuminating Engineering Society', 5);
INSERT INTO clubs_categories (club_id, category_id) VALUES (520, 2);
INSERT INTO clubs (club_name, members) VALUES ('Institute of Electrical and Electronics Engineers', 10);
INSERT INTO clubs_categories (club_id, category_id) VALUES (521, 2);
INSERT INTO clubs (club_name, members) VALUES ('Integrative Physiology Club', 6);
INSERT INTO clubs_categories (club_id, category_id) VALUES (522, 2);
INSERT INTO clubs (club_name, members) VALUES ('Kappa Theta Pi', 1);
INSERT INTO clubs_categories (club_id, category_id) VALUES (523, 2);
INSERT INTO clubs (club_name, members) VALUES ('LeetCode Club', 7);
INSERT INTO clubs_categories (club_id, category_id) VALUES (524, 2);
INSERT INTO clubs (club_name, members) VALUES ('Materials Research Society', 22);
INSERT INTO clubs_categories (club_id, category_id) VALUES (525, 2);
INSERT INTO clubs (club_name, members) VALUES ('National Society of Black Engineers', 9);
INSERT INTO clubs_categories (club_id, category_id) VALUES (526, 2);
INSERT INTO clubs (club_name, members) VALUES ('Neuroscience Club', 61);
INSERT INTO clubs_categories (club_id, category_id) VALUES (527, 2);
INSERT INTO clubs (club_name, members) VALUES ('oSTEM @ the University of Colorado, Boulder', 21);
INSERT INTO clubs_categories (club_id, category_id) VALUES (528, 2);
INSERT INTO clubs (club_name, members) VALUES ('Pre-Vet Club', 2);
INSERT INTO clubs_categories (club_id, category_id) VALUES (529, 2);
INSERT INTO clubs (club_name, members) VALUES ('Psychedelic Club', 139);
INSERT INTO clubs_categories (club_id, category_id) VALUES (530, 2);
INSERT INTO clubs (club_name, members) VALUES ('Public Health Hub', 8);
INSERT INTO clubs_categories (club_id, category_id) VALUES (531, 2);
INSERT INTO clubs (club_name, members) VALUES ('REDTAC Squadron - The Composite Aircraft Build At CU', 6);
INSERT INTO clubs_categories (club_id, category_id) VALUES (532, 2);
INSERT INTO clubs (club_name, members) VALUES ('Science Community Outreach Program and Education', 3);
INSERT INTO clubs_categories (club_id, category_id) VALUES (533, 2);
INSERT INTO clubs (club_name, members) VALUES ('Science Under The Dome (SciDome)', 18);
INSERT INTO clubs_categories (club_id, category_id) VALUES (534, 2);
INSERT INTO clubs (club_name, members) VALUES ('Server Development', 4);
INSERT INTO clubs_categories (club_id, category_id) VALUES (535, 2);
INSERT INTO clubs (club_name, members) VALUES ('Society for Industrial and Applied Mathematics Graduate Chapter', 5);
INSERT INTO clubs_categories (club_id, category_id) VALUES (536, 2);
INSERT INTO clubs (club_name, members) VALUES ('Society of Asian Scientists and Engineers', 5);
INSERT INTO clubs_categories (club_id, category_id) VALUES (537, 2);
INSERT INTO clubs (club_name, members) VALUES ('Society of Hispanic Professional Engineers', 7);
INSERT INTO clubs_categories (club_id, category_id) VALUES (538, 2);
INSERT INTO clubs (club_name, members) VALUES ('Society of Women Engineers CU Boulder', 58);
INSERT INTO clubs_categories (club_id, category_id) VALUES (539, 2);
INSERT INTO clubs (club_name, members) VALUES ('Solar Decathlon', 20);
INSERT INTO clubs_categories (club_id, category_id) VALUES (540, 2);
INSERT INTO clubs (club_name, members) VALUES ('STEM Routes', 12);
INSERT INTO clubs_categories (club_id, category_id) VALUES (541, 2);
INSERT INTO clubs (club_name, members) VALUES ('STEMinar', 2);
INSERT INTO clubs_categories (club_id, category_id) VALUES (542, 2);
INSERT INTO clubs (club_name, members) VALUES ('Strategies for Ecology, Education, Diversity and Sustainability', 6);
INSERT INTO clubs_categories (club_id, category_id) VALUES (543, 2);
INSERT INTO clubs (club_name, members) VALUES ('Supra: A Space Force Club', 14);
INSERT INTO clubs_categories (club_id, category_id) VALUES (544, 2);
INSERT INTO clubs (club_name, members) VALUES ('T9hacks', 6);
INSERT INTO clubs_categories (club_id, category_id) VALUES (545, 2);
INSERT INTO clubs (club_name, members) VALUES ('Tau Beta Pi', 3);
INSERT INTO clubs_categories (club_id, category_id) VALUES (546, 2);
INSERT INTO clubs (club_name, members) VALUES ('The Flying Club at CU', 27);
INSERT INTO clubs_categories (club_id, category_id) VALUES (547, 2);
INSERT INTO clubs (club_name, members) VALUES ('Theta Tau', 10);
INSERT INTO clubs_categories (club_id, category_id) VALUES (548, 2);
INSERT INTO clubs (club_name, members) VALUES ('Women in Construction', 7);
INSERT INTO clubs_categories (club_id, category_id) VALUES (549, 2);
INSERT INTO clubs (club_name, members) VALUES ('Women in Cybersecurity (WiCyS - CU Boulder Chapter)', 5);
INSERT INTO clubs_categories (club_id, category_id) VALUES (550, 2);
INSERT INTO clubs (club_name, members) VALUES ('Women of Aeronautics and Astronautics', 29);
INSERT INTO clubs_categories (club_id, category_id) VALUES (551, 2);
INSERT INTO clubs (club_name, members) VALUES ('Women of Color in STEM', 14);
INSERT INTO clubs_categories (club_id, category_id) VALUES (552, 2);
INSERT INTO clubs (club_name, members) VALUES ('Center for Student Involvement', 7);
INSERT INTO clubs_categories (club_id, category_id) VALUES (553, 9);
INSERT INTO clubs (club_name, members) VALUES ('The Bold Center', 9);
INSERT INTO clubs_categories (club_id, category_id) VALUES (554, 9);
INSERT INTO clubs (club_name, members) VALUES ('University Memorial Center', 2);
INSERT INTO clubs_categories (club_id, category_id) VALUES (555, 9);
INSERT INTO clubs (club_name, members) VALUES ('Conference on World Affairs', 26);
INSERT INTO clubs_categories (club_id, category_id) VALUES (556, 9);
INSERT INTO clubs (club_name, members) VALUES ('CU GOLD (Gaining Opportunities through Leadership Development)', 46);
INSERT INTO clubs_categories (club_id, category_id) VALUES (557, 9);
INSERT INTO clubs (club_name, members) VALUES ('Cultural Events Board', 119);
INSERT INTO clubs_categories (club_id, category_id) VALUES (558, 9);
INSERT INTO clubs (club_name, members) VALUES ('Distinguished Speakers Board', 9);
INSERT INTO clubs_categories (club_id, category_id) VALUES (559, 9);
INSERT INTO clubs (club_name, members) VALUES ('INFO Buffs', 6);
INSERT INTO clubs_categories (club_id, category_id) VALUES (560, 9);
INSERT INTO clubs (club_name, members) VALUES ('Leeds Dean's Student Cabinet', 6);
INSERT INTO clubs_categories (club_id, category_id) VALUES (561, 9);
INSERT INTO clubs (club_name, members) VALUES ('The Herd Leadership Council', 29);
INSERT INTO clubs_categories (club_id, category_id) VALUES (562, 9);
