INSERT INTO reviews (text, rating, user_id, club_id)
SELECT 'Great club, highly recommend!', 5, 1, 2
WHERE NOT EXISTS (
    SELECT 1 FROM reviews WHERE text = 'Great club, highly recommend!'
);
    
INSERT INTO reviews (text, rating, user_id, club_id)
SELECT 'Not the best experience, would not join again', 2, 3, 4
WHERE NOT EXISTS (
    SELECT 1 FROM reviews WHERE text = 'Not the best experience, would not join again'
);

INSERT INTO reviews (text, rating, user_id, club_id)
SELECT 'This club changed my life!', 4, 2, 1
WHERE NOT EXISTS (
    SELECT 1 FROM reviews WHERE text = 'This club changed my life!'
);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('1825','Religion & Spirituality','7:00pm','2221 Stonehenge Circle Lafayette',6);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('4Ukraine','Social Justice, Advocacy, & Activism',NULL,NULL,5);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Adobe Creative Club','Art, Music, & Performance','Not decidesd yet','Not decidesd yet',3);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Advertising Club','Business & Entrepreneurship','7 - 8 pm Every other Tuesday','ARMORY',101);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Aerospace Medicine Student and Resident Organization','STEM',NULL,NULL,20);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('African Students Association','Cultural and International','6:30 PM','C4C N320',27);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('aiesec','Cultural and International','Thursdays 4:30-5:30pm','UMC 404',7);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Alpha Chi Omega','Greek Life, Fraternities, & Sororities',NULL,NULL,17);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Alpha Delta Chi','Greek Life, Fraternities, & Sororities',NULL,NULL,4);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Alpha Epsilon Delta','Honor Society','Every Sunday at 6:30-7:30pm for actives (6-7:30pm for new members)','HUMN 1B90',33);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Alpha Kappa Psi','Business & Entrepreneurship','6:30 PM','Koebel Room TBD',10);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Alpha Phi','Greek Life, Fraternities, & Sororities',NULL,NULL,7);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Alpha Phi Omega - Gamma Theta','Community Service & Volunteerism',NULL,NULL,5);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Alpine Club at CU','Recreation & Wellness','We meet once a semester for a larger meeting, and then weekly for other events.','Campus, Boulder, Boulder area climbing areas, and other climbing areas around the west.',239);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('American Association of Engineers of Indian Origin - University of Colorado - Boulder','STEM',NULL,NULL,6);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('American Conservation Coalition Boulder','Environmental','4th Wednesday of every month @ 7pm','HLMS 104-CC',38);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('American Indian Science and Engineering Society','STEM','Every other Tuesday 6-7 pm MST','Bold Center in EC or Zoom',6);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('American Institute of Aeronautics and Astronautics - CU Boulder Branch','STEM',NULL,NULL,54);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('American Institute of Chemical Engineers (AIChE)','STEM',NULL,'JSCBB Building',32);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('American Medical Student Association','STEM','6:00pm Every Monday','HUMN 135',151);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('American Medical Women''s Association','STEM','Wednesdays 6-7pm','CASE E240',94);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('American Meteorological Society Student Chapter','STEM',NULL,NULL,10);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('American Planning Association for Students','Humanities and Social Sciences','Tuesdays @5pm (monthly)','Third Floor of ENVD',7);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('American Sign Language Club','Social',NULL,NULL,111);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('American Society for Engineering Management','STEM','Varies','Varies',28);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('American Society of Civil Engineers','STEM','6-7 pm on Thursdays','ECCR 131',18);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('American Society of Mechanical Engineers','STEM',NULL,NULL,27);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Amuse Creative Writing Club','Art, Music, & Performance','4:00 PM Fridays','Varies',104);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Andrews Hall','Residence Life',NULL,NULL,13);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Anthropology Club','Humanities and Social Sciences','Wednesdays 5:30- 6:30pm','Hale Fourth Floor Library-- room 450',25);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Anthropology Graduate Student Association','Graduate and Professional Studies','Monthly (exact dates tbd)','Remote (Zoom) and in person',11);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Antimicrobial Resistance Mediation OutReach','STEM','Wednesdays 5-6pm','We either meet in JSCBB B1B90 or over Zoom - email us for the link!',20);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Aqua Buffs','Recreation & Wellness',NULL,NULL,14);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Arab Law Student Association','Law & Law School',NULL,NULL,3);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Armenian Student Association','Cultural and International',NULL,NULL,5);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Arnett Hall','Residence Life',NULL,NULL,10);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Arnold Air Society - Onizuka Squadron','Community Service & Volunteerism','Varies','Varies',20);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Arts and Sciences Student Government','Governing Body',NULL,NULL,22);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Asian American InterVarsity','Religion & Spirituality','Every Thursday at 7pm','HUMN 190',10);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Asian American Literature Association','Cultural and International',NULL,NULL,5);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Asian Pacific American Law Students Association','Law & Law School',NULL,NULL,3);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Asian Unity','Cultural and International','Wednesday at 5:30 pm','ECCR 1B40',83);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Assembly Language Club','STEM','Fridays from 7pm to 8pm','The Engineering Center in the Computer Science Department',7);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Association for Students with Disabilities','Social','Every other Wednesday from 5:30 pm-7:00 pm, starting Jan 25, 2023','Abram''s Lounge on the Third Floor of the C4C',17);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Association of Latino Professionals For America','Business & Entrepreneurship','5:00pm','KOBL',6);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('ATOC Graduate Students','Graduate and Professional Studies',NULL,NULL,16);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('B-Corp Club','Business & Entrepreneurship',NULL,NULL,9);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Backcountry Club at CU','Recreation & Wellness',NULL,NULL,252);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Backcountry Squatters','Recreation & Wellness','8:00 PM Tuesdays','Bi-weekly Zoom',134);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Baker Community Council','Residence Life',NULL,NULL,1);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Baker Hall','Residence Life',NULL,NULL,16);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Balkan Student Association','Cultural and International',NULL,NULL,3);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Bandana Project','Social Justice, Advocacy, & Activism','TBD','TBD',8);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Be the Match on Campus','Community Service & Volunteerism',NULL,NULL,14);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Bear Creek & Weber Hall','Residence Life',NULL,NULL,17);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Bear Creek Community Council','Residence Life',NULL,NULL,6);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Best Buddies at CU','Social',NULL,NULL,89);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Beta Theta Pi','Greek Life, Fraternities, & Sororities',NULL,NULL,13);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Bhakti Yoga Club','Religion & Spirituality','Wednesdays 6 PM','HLMS 191',71);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Biomedical Engineering Society','STEM','Tuesdays at 6 pm','TBD',35);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Bitcoin Buffs','Business & Entrepreneurship','5pm Tuesdays','TBD',10);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Black Christians at CU','Religion & Spirituality','6:30','TBD',13);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Black Graduate and Professional Student Association','Graduate and Professional Studies',NULL,NULL,15);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Black Law Student Association','Law & Law School','Wednesdays 12pm',NULL,6);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Black Student Alliance','Social Justice, Advocacy, & Activism',NULL,NULL,102);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Blueprint Boulder','STEM',NULL,NULL,16);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Boulder Athletic Management Club','Community Service & Volunteerism',NULL,NULL,5);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Boulder Barefoot Walkers','Recreation & Wellness',NULL,NULL,23);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Boulder Bole Bhangra','Cultural and International','Tuesday and Thursday 8-10pm','Rec Center or Will Vill Rec Center',3);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Boulder Campus Ministry','Religion & Spirituality','Wednesdays @7pm','Varies - Text or email for details',8);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Boulder Film Buffs','Social','Tuesdays 7:00','TBD',32);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Boulder Freeride','Recreation & Wellness',NULL,NULL,507);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Boulder Lifting Club','Recreation & Wellness','Thursdays, 6:30PM- Group lifts; Fridays, 6:30PM - Bulk Days; Saturdays, 6;30PM- Group lifts','University Of Colorado Boulder Recreation Center',174);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Boulderite Chess Club','Social','Every Monday 6:30-8:00 pm','Ketchum Arts and Sciences 1B71',130);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Brazilian Student Association at the University of Colorado Boulder','Cultural and International',NULL,NULL,34);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Breakthrough Student Group','Law & Law School',NULL,NULL,3);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Bridges International','Religion & Spirituality',NULL,NULL,3);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Buckingham Hall','Residence Life',NULL,NULL,11);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Buff Axes','Recreation & Wellness','TBD',NULL,30);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Buff Brain Gym','Recreation & Wellness','7:00pm','HLMS 199',6);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Buffalo Catholic','Religion & Spirituality',NULL,NULL,18);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Buffalo Country Swing','Recreation & Wellness','Wednesday 6:00-8:00','CU Boulder Recreation Center',6);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Buffoons','Art, Music, & Performance','Tues. & Thurs.',NULL,14);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Buffs Against Food Waste','Environmental',NULL,NULL,3);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Buffs for Reproductive Rights','Social Justice, Advocacy, & Activism','Mondays, 5:00pm','Hellems 104',73);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Buffs Going Bananas','Social',NULL,NULL,46);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Buffs4Israel','Cultural and International',NULL,'CU Boulder Hillel',8);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Campus Crusade for Christ','Religion & Spirituality',NULL,NULL,6);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Campus Reproductive Resources','Recreation & Wellness',NULL,NULL,4);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Cannabis Law League','Law & Law School',NULL,NULL,5);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('CannaBuffs','Business & Entrepreneurship',NULL,NULL,133);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Capoeira Club','Recreation & Wellness','Thursdays 6:00-7:30 PM','Rec Center Studio 1',13);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Caving Club','Recreation & Wellness',NULL,NULL,94);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Center for Student Involvement','University Programs',NULL,NULL,7);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('CESR Fellows','Business & Entrepreneurship','Wednesdays at 6:30pm','Koelbl Room 341',7);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('CHAARG','Recreation & Wellness','Thursday 7:30 -8:30 pm','TBA in Weekly Newsletters',17);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Chem and Biochem Club','STEM','Every other Wednesday, 5:30pm','Ekeley M339',45);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('CHEMunity','Graduate and Professional Studies',NULL,NULL,6);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Cheyenne Arapaho Community Council','Residence Life',NULL,NULL,4);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Cheyenne Arapaho Hall','Residence Life',NULL,NULL,17);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Chi Alpha','Religion & Spirituality','Thursdays at 7:00','TBD',4);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Chi Omega','Greek Life, Fraternities, & Sororities',NULL,NULL,13);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Chinese Students and Scholars Association','Cultural and International',NULL,NULL,23);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Christian Buffalo Fellowship','Religion & Spirituality',NULL,NULL,4);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Christian Challenge','Religion & Spirituality','Wednesday @7PM','TBD',4);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Christian Legal Society','Religion & Spirituality',NULL,'Wolf Law',4);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Circle K International','Community Service & Volunteerism','6:30PM Alternate Wednesdays','CASE E260',17);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Circuit Benders','Art, Music, & Performance',NULL,NULL,14);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Class of 2025 Board','Law & Law School','12:00pm','Wolf Law',7);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('CMCI Student Government','Governing Body',NULL,NULL,22);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Coding Buffs','STEM',NULL,NULL,2);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Coffee Club','Social','9:30','TBD',70);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Collar Scholars','Community Service & Volunteerism','Updates on time and location will be posted in GroupMe, send us an email with your phone number and we will add you to it!','Updates on time and location will be posted in GroupMe, send us an email with your phone number and we will add you to it!',295);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('College of Music Student Government','Governing Body',NULL,NULL,2);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Colorado Bhangra Team','Art, Music, & Performance',NULL,NULL,12);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Colorado Credit Capital','Business & Entrepreneurship','6 - 7 pm on Tuesdays','KOBL 125/217 (Varies)',6);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Colorado Delta Chi','Greek Life, Fraternities, & Sororities',NULL,NULL,2);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Colorado Disability Justice Alliance','Law & Law School',NULL,NULL,3);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Colorado Engineer Magazine','STEM',NULL,NULL,2);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Colorado Evans Scholars','Social',NULL,NULL,5);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Colorado Homeless Assistance with Medicine Program','Community Service & Volunteerism','Tuesdays at 6:00 pm',NULL,27);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Colorado Investment Management Society','Business & Entrepreneurship','Wednesday 4 to 5','1100 Pennsylvania Avenue',16);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Colorado Law Adventure Club','Recreation & Wellness',NULL,NULL,6);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Colorado Law Animal Legal Defense Fund','Law & Law School',NULL,NULL,3);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Colorado Ocean Coalition','Environmental','Biweekly: Tuesdays 7-8PM','DUANE G131 and Zoom Option Available',59);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Colorado Ski Racing','Recreation & Wellness',NULL,NULL,12);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Colorado WASH Symposium','STEM','Mondays 2-3pm','Zoom link available upon request',5);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Committee for Equity in Mechanical Engineering','Social Justice, Advocacy, & Activism','Once a month on Wednesday at 12:00','TBD',3);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Competitive Programming and Career Building Club','STEM','Wednesdays at 6:00pm','Join our Discord server',72);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Computer Science Graduate Professional Development Club','Graduate and Professional Studies','Mondays 5:00 to 6:00 PM','ECCR 150 and https://cuboulder.zoom.us/my/csgpdc',34);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Computer Science Graduate Student Association','STEM','Mondays at noon','Zoom/ECES 112 as available',10);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Conference on World Affairs','University Programs',NULL,NULL,26);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Cooking Through Cultures','Cultural and International','Sundays','Will Vill East Kitchen',13);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Crave the Sound','Art, Music, & Performance','General Meetings Every Monday at 6:15','Zoom',28);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Creative Nonfiction Club','Humanities and Social Sciences',NULL,NULL,9);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Creo','Art, Music, & Performance','5:30 P.M. on Wednesdays','Norlin Library',3);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Crochet and Conversation','Social','Fridays 5pm - 6:30 pm','HUMN 160',136);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('CSI Test Organization','Graduate and Professional Studies','9AM - 10AM','CSI Office',1);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('CU Abhinaya','Art, Music, & Performance','Tuesday and Thursday (7:00-9:30pm)','CU REC',3);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('CU American Marketing Association','Business & Entrepreneurship','Tuesdays at 6:30pm','Koelbel 218',70);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('CU American String Teachers Association','Art, Music, & Performance','Varies','CU College of Music',1);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('CU Anime Club','Social','5pm every Friday','CUAC Discord + Hellems 201',74);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('CU Astronomy Club','STEM','Friday Evening: Time Varies','Varies',10);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('CU BioStatistics and Public Health Club','STEM',NULL,NULL,5);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('CU Blockchain','STEM','2:00 PM','CSEL',41);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('CU Board Game Club','Social','Tuesdays at 6pm and Saturdays at 2pm','UMC Cafeteria or other UMC rooms. Join our discord (https://discord.gg/V9KhgZB) or mailing list for specifics.',55);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('CU Book Club','Social','TBD','TBD',73);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('CU Boulder Asian Studies Graduate Association','Graduate and Professional Studies','Meetings when needed','On Zoom',2);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('CU Boulder Chapter of the American Water Resources Association','Environmental','9/1/2022','Guggenheim Geography/SEEC/Zoom',33);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('CU Boulder Collegiate Chapter of MTNA','Art, Music, & Performance','1PM on Fridays','IMIG Music Building',14);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('CU Boulder Comedy Club','Art, Music, & Performance',NULL,NULL,12);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('CU Boulder Cosplay Club','Art, Music, & Performance','Mondays 5:00Pm - 7:00PM',NULL,5);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('CU Boulder Democrats','Government & Politics','6-7 pm on Tuesdays','Eaton Humanities (Room 190)',12);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('CU Boulder Energy and Sustainability Society','Environmental','Every other Monday from 6:45pm-7:45pm','UMC 418',24);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('CU Boulder Esports','Recreation & Wellness',NULL,NULL,48);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('CU Boulder Gymnastics Club','Recreation & Wellness',NULL,NULL,9);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('CU Boulder Hillel','Religion & Spirituality',NULL,'CU Boulder Hillel',29);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('CU Boulder Ice Skating Club','Recreation & Wellness','Tuesday 6-7pm','Clare Small Room 104',106);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('CU Boulder iGem Team','STEM',NULL,NULL,5);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('CU Boulder Marxists','Social Justice, Advocacy, & Activism','Mondays 5:45pm-7pm','HUMN 186',15);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('CU Boulder Milana','Cultural and International','Monday, Wednesday & Thursday (8:00-10:00pm)','CU Rec Center',14);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('CU Boulder Racing Team','STEM',NULL,NULL,205);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('CU Boulder Railroad Club','Social','Wednesdays 6:00 PM','Idea Forge Commons',7);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('CU Boulder RoboSub Team','STEM','Thursday September 1st','Buff Pool',19);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('CU Boulder Salesforce Student Group','Business & Entrepreneurship','Wednesdays 11:30-12:30PM (1st + 3rd Weeks) & 5-6PM (2nd + 4th Weeks) see CUSalesforce.com for dates.','KOBL 235',5);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('CU Boulder Swing Dance','Recreation & Wellness','7-10pm','Rec Center: Large Ice Rink Overlook Meeting Room',44);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('CU Breaking Club','Art, Music, & Performance','8:30 PM','CU Rec Center',12);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('CU Bridge Buffs','Cultural and International','Tuesdays, 7-8pm','Kitt Central South, email bridgebuffs@colorado.edu for location confrimation',12);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('CU Bridge Club','Recreation & Wellness','Monday 5-7 PM','HUME 190 Or UMC 386',11);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('CU Burlesque','Art, Music, & Performance',NULL,NULL,58);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('CU Catalan Club','Cultural and International','Monthly','In person',5);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('CU Ceramics Club','Art, Music, & Performance','TBT - meeting will be posted on organization''s page','ZOOM',98);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('CU Citizens'' Climate Lobby','Government & Politics','TBA','TBA',28);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('CU Climbing Team','Recreation & Wellness',NULL,NULL,23);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('CU Club Golf','Recreation & Wellness',NULL,NULL,13);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('CU College Republicans','Government & Politics','Thursday 6:00 PM MT - 7:00 PM MT','KOBL 342',36);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('CU Cornhole Club','Social','Thursdays 6:00pm','Farrand Field',141);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('CU CRICKET','Recreation & Wellness',NULL,NULL,20);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('CU Cyber Club','STEM','Every Wednesday @ 5pm ( 8/31/2022 ~ 12/07/2022)','8/31~12/07 (DLC 1B20)',13);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('CU Dance Party','Recreation & Wellness','5-6 Wednesdays',NULL,1);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('CU Disc Golf','Recreation & Wellness',NULL,NULL,54);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('CU Dungeons and Dragons','Social',NULL,'https://discord.gg/Y7yzUhxBsw',103);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('CU ED Support Group','Recreation & Wellness','Mondays 7-8pm','Hellems 137',3);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('CU Energy Club','Environmental',NULL,NULL,104);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('CU Engineering World Health','STEM',NULL,NULL,6);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('CU Equestrian Team','Recreation & Wellness',NULL,NULL,17);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('CU Farm & Garden Club','Environmental',NULL,NULL,104);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('CU Freeskiing Team','Recreation & Wellness',NULL,NULL,94);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('CU Gaelic Club','Recreation & Wellness',NULL,NULL,6);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('CU Game Development and Graphics Club','Art, Music, & Performance','6:00 - 7:00 PM','DUAN G1B27',23);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('CU Gaming','Recreation & Wellness',NULL,'UMC 134',157);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('CU GOLD (Gaining Opportunities through Leadership Development)','University Programs',NULL,NULL,46);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('CU Hyperloop','STEM','All-Team at 4 pm on Sundays','Engineering Center',12);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('CU Independent','Art, Music, & Performance','Sundays at 7 p.m.','CASE W262',2);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('CU International','Cultural and International',NULL,NULL,27);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('CU Jam Society','Art, Music, & Performance','Tuesdays at 7:30','The Connection',42);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('CU Juggling Club','Recreation & Wellness','4:00-6:00pm','Farrand Field. In case of cold or bad weather, meetings take place in the lobby of Carlson Gymnasium.',12);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('CU Kathak and Folk Dance Club','Social','5-6 pm','UMC 457',1);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('CU Law Class of 2023','Law & Law School',NULL,NULL,4);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('CU Linguistics Club','Humanities and Social Sciences','Mondays at 6:00 PM','Linguistics Conference Room (Hellems 285)',17);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('CU Mock Trial','Law & Law School',NULL,NULL,39);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('CU Model United Nations','Humanities and Social Sciences','6:00pm weekly on Thursdays','Muensinger E113',24);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('CU Mountain Biking','Recreation & Wellness',NULL,NULL,4);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('CU Museum Club','STEM','TBD','In-Person/Zoom',9);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('CU Mycology Club','STEM',NULL,NULL,89);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('CU On The Rocks','Art, Music, & Performance','Sundays & Wednesdays, 7:00-9:00','Hellems',9);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('CU Physician Assistant Club','STEM',NULL,NULL,22);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('CU Physics Olympiad','STEM',NULL,NULL,3);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('CU Poker Club','Recreation & Wellness','7-8pm','Koebel',63);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('CU Political Science Club','Government & Politics','Tuesdays at 5:30pm','Hellems Room 211',39);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('CU Powerlifting','Recreation & Wellness','Thursdays @ Rec Center - 6:00pm | Fridays @ Gym5 - 6:30pm','CU Rec Center & Gym 5',97);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('CU Pre-Dental Society','Graduate and Professional Studies',NULL,NULL,4);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('CU Psychology Club','Humanities and Social Sciences','Wednesdays, 6:00pm','In-person/Zoom',236);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('CU Quadball','Recreation & Wellness','10:00-12:00 Sundays','Duane Lawn',15);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('CU Quants','Business & Entrepreneurship','5:00 - 6:00 pm','KOBL 312',14);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('CU Quiz Bowl','Humanities and Social Sciences','Wednesdays 6:15-9 PM','Duane G131',8);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('CU Racquetball','Recreation & Wellness',NULL,NULL,1);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('CU Rave Club','Art, Music, & Performance','Bi-weekly Tuesdays (starting 8/30) @7:00PM','HUMN 250',141);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('CU Real Estate Club','Business & Entrepreneurship','Wednesdays 6:30 pm','KOBL 102',45);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('CU Robotics','STEM','Saturdays (4:00-7:00pm) & Tuesdays(6:30-9:30pm)','CU Idea Forge',64);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('CU Rotaract Club','Community Service & Volunteerism','Wednesdays @ 6:30pm','Hellems 137',14);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('CU Rover Team','STEM','Weekly on Tuesdays at 5:00pm','Discord',29);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('CU Sailing','Recreation & Wellness',NULL,NULL,43);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('CU Social Psychology Lab','STEM',NULL,NULL,21);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('CU Sounding Rocket Laboratory','STEM','7:00 PM on Thursday','zoom - cu-srl.slack.com',165);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('CU Sports Career Group','Business & Entrepreneurship',NULL,NULL,7);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('CU Student Academy of Audiology','Graduate and Professional Studies','1:00-2:00 first Monday of the Month','wold law building 306',17);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('CU Student Chapter of the Society of American Military Engineers','STEM',NULL,NULL,5);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('CU Student Government','Governing Body',NULL,NULL,54);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('CU Students for the Exploration and Development of Space','STEM',NULL,NULL,14);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('CU Technology for Extreme Environments','STEM','5-7pm Wednesdays','Aerospace Building',8);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('CU Watermelon Club','Recreation & Wellness','TBD','TBD',49);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('CU Wildlife Club','Environmental',NULL,NULL,174);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('CU Wind Energy Club','STEM','6-7 PM First Wednesday every Month',NULL,8);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('CU Windsports Club','Recreation & Wellness',NULL,NULL,8);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('CU Women in Computing','STEM',NULL,NULL,28);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('CU Wrestling Club','Recreation & Wellness','11am-1pm Tuesday/Thursday','Mat Room (CU Rec Center)',22);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('CU-Prime','STEM',NULL,NULL,7);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Cultural Events Board','University Programs',NULL,NULL,119);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Culture, Language, and Social Practice Program (CLASP)','Humanities and Social Sciences',NULL,NULL,5);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Darley Community Council','Residence Life',NULL,NULL,4);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Darley Towers','Residence Life',NULL,NULL,17);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Data Buffs','STEM',NULL,NULL,35);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Data Science Student Association','STEM',NULL,NULL,9);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Delta Delta Delta','Greek Life, Fraternities, & Sororities',NULL,NULL,3);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Delta Gamma Sorority','Greek Life, Fraternities, & Sororities',NULL,NULL,3);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Delta Rho Chapter of Mu Phi Epsilon','Art, Music, & Performance','TBA','TBA',2);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Delta Sigma Phi','Greek Life, Fraternities, & Sororities',NULL,NULL,20);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Delta Sigma Pi','Business & Entrepreneurship','8-9 pm on Tuesdays','KOBL 225',8);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Delta Tau Delta','Greek Life, Fraternities, & Sororities',NULL,NULL,5);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Delta Upsilon','Greek Life, Fraternities, & Sororities',NULL,NULL,5);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Design Build Fly','STEM',NULL,NULL,31);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Design for America','STEM',NULL,NULL,4);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Design Your Path LLC','Residence Life',NULL,NULL,2);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Disability Advocacy Student Union','Social Justice, Advocacy, & Activism',NULL,NULL,11);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Distinguished Speakers Board','University Programs',NULL,NULL,9);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Drag Buffs','Social','4pm - Fridays','Check Discord - Zoom ID: 8367794235',25);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Earth Muffins','Art, Music, & Performance','Tuesdays at 5:30 p.m.','ATLAS 1b31',4);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Earthquake Engineering Research Institute','STEM','Varies (contact us for more info!)',NULL,1);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('EcoReps: Sustainability Leadership Program','Environmental',NULL,NULL,37);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Electrochemical Society at CU Boulder','STEM',NULL,NULL,4);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Elevation','Art, Music, & Performance','Friday and Sundays at 7-9pm','Rec Center Dance Studio',5);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Elohim Academy','Religion & Spirituality','5:00 Thursdays','C.A.S.E Building',3);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Emeralds of Kappa Delta Chi Sorority, Inc.','Greek Life, Fraternities, & Sororities',NULL,NULL,12);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Emergency Painting','Art, Music, & Performance',NULL,NULL,6);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('enACTs','Art, Music, & Performance','Monthly','THDN',2);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('End Overdose at CU Boulder','Social Justice, Advocacy, & Activism',NULL,NULL,16);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Engineers Without Borders','Community Service & Volunteerism',NULL,NULL,113);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('English Graduate Student Council','Graduate and Professional Studies',NULL,NULL,3);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Environmental Design Student Government','Governing Body',NULL,NULL,4);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Environmental Law Society','Law & Law School',NULL,'Wolf Law Building',6);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Euchre Club','Social',NULL,NULL,3);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Evening MBA Association','Business & Entrepreneurship',NULL,NULL,3);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Extreme Measures A Cappella','Art, Music, & Performance','7-9PM TTh, 4-6 Sun','HLMS 211',8);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Family and Juvenile Law Club','Law & Law School',NULL,NULL,3);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Farrand Community Council','Residence Life',NULL,NULL,2);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Farrand Hall','Residence Life',NULL,NULL,11);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Federalist Society for Law and Public Policy Studies','Law & Law School',NULL,NULL,2);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('FHL Chinese Christian Fellowship','Religion & Spirituality',NULL,NULL,2);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Financial Planning Club','Business & Entrepreneurship','6-7 PM on Tuesdays (Weekly)','KOBL 323',12);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Food For Thought','Cultural and International','TBD','TBD',8);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Fossil Free CU','Social Justice, Advocacy, & Activism','Monday 6:30-7:30','Over Zoom',5);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('FPV Society At CU Boulder','STEM',NULL,NULL,6);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('French Club','Cultural and International',NULL,NULL,29);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Friends of Doctors Without Borders at CU Boulder','Cultural and International','Alternating Mondays, 5-6pm','KOBL 140',17);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Gamma Phi Beta','Greek Life, Fraternities, & Sororities',NULL,NULL,2);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Gender & Sexuality Alliance','Social','8:00PM MST','JD Abrams Lounge (3rd floor, C4C)',73);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Generation Exchange','Community Service & Volunteerism',NULL,NULL,3);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Geological Sciences Graduate Association','Graduate and Professional Studies',NULL,NULL,12);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Global Dental Brigades','Community Service & Volunteerism',NULL,NULL,5);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Global Medical Brigades','Community Service & Volunteerism','Wednesdays at 6:00pm','TBD',17);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Global Surgery Student Alliance at CU Boulder','STEM','5:30- 6:30','Refer to Discord/ Social Media',5);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Good Grief!','Social','5 PM, Fridays','Farrand Field (under the sign!) or Zoom (as a backup)',14);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Google Developer Student Clubs University of Colorado Boulder','STEM',NULL,NULL,3);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Graduate and Professional Student Government','Governing Body',NULL,NULL,8);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Graduate Musicology Society','Art, Music, & Performance',NULL,NULL,21);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Grand Canonical Ensemble','Art, Music, & Performance','We meet for 1-2 hours once a week throughout the semester for rehearsals / jam time; exact time depending on people''s schedules and availability.',NULL,10);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Greek Club','Cultural and International',NULL,NULL,1);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Green Consulting Group','Environmental',NULL,NULL,4);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('HackCU','STEM',NULL,NULL,6);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Hallett Community Council','Residence Life',NULL,NULL,3);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Hallett Hall','Residence Life',NULL,NULL,18);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Health Equity and Applied Learning','Social Justice, Advocacy, & Activism','Mondays, 7:30-8:30pm','Duane G2B41',27);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Health Law Society','Law & Law School',NULL,NULL,6);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Hiking Club at CU Boulder','Recreation & Wellness',NULL,NULL,293);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Hindu YUVA','Cultural and International',NULL,NULL,11);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Historical European Martial Arts at CU','Recreation & Wellness','10:00','Martin Park (south Boulder)',16);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('History Club','Humanities and Social Sciences','Tuesday''s from 5:30pm-7:00pm','Hellems 181',45);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('History Graduate Student Association','Humanities and Social Sciences',NULL,NULL,2);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Honor Guard','Social','tbh','tbh',3);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Honors Journal Editorial Board','Humanities and Social Sciences',NULL,NULL,5);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('HOSA - Future Health Professionals','STEM','monthly, 6pm','Gold A152',14);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Humans versus Zombies at CU Boulder','Social',NULL,NULL,1);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('If/When/How: Lawyering For Reproductive Justice','Law & Law School',NULL,NULL,5);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Illuminating Engineering Society','STEM',NULL,NULL,5);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Immigration Law and Policy Society','Law & Law School',NULL,NULL,3);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('In The Buff A Cappella','Art, Music, & Performance','SunMW','UMC',11);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Indian Students Association','Cultural and International',NULL,NULL,103);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Industrial Design Society of America CU Boulder','Environmental',NULL,NULL,7);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('INFO Buffs','University Programs',NULL,NULL,6);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Information Science Graduate Student Association','Graduate and Professional Studies','Last Wednesday of Every Month @ 3pm','Zoom [virtual] and INFO Science Building',5);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Institute of Electrical and Electronics Engineers','STEM','6:30 PM Wednesday Monthly','on Campus',10);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Integrative Physiology Club','STEM',NULL,NULL,6);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Interfraternity Council','Governing Body',NULL,NULL,12);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('International Aerospace Students Association','Social Justice, Advocacy, & Activism',NULL,NULL,5);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('International Festival Committee','Cultural and International','4:00pm-5:00pm on Thursdays','Center for Community S350',10);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('International Moot Court','Law & Law School','Tbd','Wolf Law',4);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('InterVarsity Graduate Christian Fellowship','Religion & Spirituality',NULL,NULL,7);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Iranian Students at CU Boulder','Social',NULL,NULL,3);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Japanese Student Association','Cultural and International','Starting 6 PM on every Thursday','Eaton Humanities HUMN125',15);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Jewish Student Association','Religion & Spirituality',NULL,'909 14th Street, Boulder CO, 80302',7);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Kappa Alpha Theta, CU Boulder','Greek Life, Fraternities, & Sororities',NULL,NULL,6);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Kappa Kappa Gamma','Greek Life, Fraternities, & Sororities',NULL,NULL,2);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Kappa Theta Pi','STEM','Monday 7:00-8:00','KOBL',1);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Kesem','Community Service & Volunteerism',NULL,NULL,11);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Kitt Central & Andrews Community Council','Residence Life',NULL,NULL,6);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Kitt West & Arnett Community Council','Residence Life',NULL,NULL,3);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Kittredge Central Hall','Residence Life',NULL,NULL,7);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Kittredge West Hall','Residence Life',NULL,NULL,10);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Korean American Student Association','Cultural and International','Every other Thursday','Hellems 199',2);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Korean Graduate Student Association','Cultural and International','3:00-4:00 PM, Every Wednesdays','Online(Zoom), In-person(TBD)',24);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Korey Wise Innocence Project Student Group','Law & Law School',NULL,NULL,1);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Kungfu Buff','Recreation & Wellness',NULL,NULL,3);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Kuwaiti Student Association','Cultural and International','TBA','TBA',4);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Laser Tag & Pancakes','Social',NULL,NULL,118);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Latinx Law Student Association','Law & Law School',NULL,NULL,4);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Latter Day Saint Student Association','Religion & Spirituality',NULL,NULL,1);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Leading Women of Tomorrow','Social Justice, Advocacy, & Activism','October 13 and every other Thursday at 5','UMC 417',30);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Leed''s Net Impact','Business & Entrepreneurship',NULL,NULL,1);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Leeds Association for Information Systems','Business & Entrepreneurship',NULL,NULL,6);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Leeds Consulting Group','Business & Entrepreneurship','7pm-9pm on Mondays','KOBL 218',17);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Leeds Dean''s Student Cabinet','University Programs',NULL,NULL,6);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Leeds Investment and Trading Group','Business & Entrepreneurship','5-6 PM','KOBL 105',116);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Leeds Outdoor Industry Club','Business & Entrepreneurship',NULL,NULL,25);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Leeds Student Government','Governing Body',NULL,NULL,13);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Leeds Venture Club','Business & Entrepreneurship','TBD - Join Email List','TBD - Join Email List',5);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('LeetCode Club','STEM','Tuesday @ 7PM','DLC 1B65',7);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Left Right Tim Improv Comedy','Art, Music, & Performance','Shows 8:30pm Every Friday','Hale 270',4);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Let''s Talk Data','Business & Entrepreneurship','4:00','Koelbel',1);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Letters of Love CU-Boulder','Community Service & Volunteerism',NULL,NULL,18);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Libby Community Council','Residence Life',NULL,NULL,23);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Libby Hall','Residence Life',NULL,NULL,14);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Lighthouse Christian Bible Study','Religion & Spirituality','5PM Fridays','UMC',4);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Lutheran Campus Ministry','Religion & Spirituality','Tuesdays at 6pm','St. Aidan''s Episcopal Church',8);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Magic: The Gathering Club','Recreation & Wellness','Mondays 6:30-10 PM, Thursdays 6-10 PM','Mondays Ketchum 1B87, Thursdays Ketchum 1B71',23);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Marvel Super Movie Club','Art, Music, & Performance','7-9PM','Eaton Humanities 1B90',52);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Materials Research Society','STEM',NULL,'SEEC N321',22);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('MBA Association','Governing Body',NULL,NULL,1);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('MECHA','Social Justice, Advocacy, & Activism','Every other Thursday, 5 p.m.','Announced on Instagram page biweekly',5);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Meridian Creative Arts Journal','Art, Music, & Performance','Varies','In-Person/Online',11);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Mile 21 A cappella','Art, Music, & Performance','10-Aug','UMC',4);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Greek Life, Fraternities, & Sororities','Greek Life, Fraternities, & Sororities',NULL,NULL,4);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Music Industry Club','Business & Entrepreneurship','Every Thursday at 7:00 pm (MST)','KOBL 102 on the 1st floor of the Koelbel Building',37);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Music Production Club','Art, Music, & Performance','Wednesday at 6:45pm to 7:45pm','Atlas Building (ATLS 104)',24);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Muslim Student Association','Religion & Spirituality','Thursdays 5:30-7','Hellems 211',22);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Mystics: Tarot and Astrology','Religion & Spirituality','Tuesdays at 6:00 pm','351UMC',74);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('NAMI on Campus at CU Boulder','Social Justice, Advocacy, & Activism','Thusdays 5:30pm','Zoom',6);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('National Association for Music Education','Art, Music, & Performance',NULL,NULL,4);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('National Lawyers Guild','Law & Law School',NULL,NULL,3);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('National Residence Hall Honorary','Community Service & Volunteerism',NULL,NULL,10);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('National Society of Black Engineers','STEM','Biweekly from 6-7 pm on Thursdays','BOLD Center in the Engineering Center',9);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('National Society of Leadership and Success','Honor Society',NULL,NULL,6);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('National Society of Pershing Rifles Company B-9','Honor Society',NULL,NULL,3);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('National Student Speech Language Hearing Association','Graduate and Professional Studies',NULL,'SLHS Building',5);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Native American Law Students Association','Law & Law School',NULL,NULL,3);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Native Graduate Student Group','Cultural and International','TBD','Zoom & In-person',8);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Navigators','Religion & Spirituality','Thursdays, 7:30 pm (under normal circumstances)',NULL,3);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Nepalese Student Association','Cultural and International','5:00pm','UMC',37);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Neuroscience Club','STEM','Tuesdays at 5pm (biweekly)','TBD',61);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('New Era Colorado','Social Justice, Advocacy, & Activism',NULL,NULL,7);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Non-Traditional Student Organization','Cultural and International',NULL,NULL,10);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Nutrition Buffs','Recreation & Wellness','5:00pm','Hellems 137',64);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Omega Chi Epsilon - Alpha Xi Chapter','Honor Society',NULL,NULL,4);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Omega Psi Phi Fraternity, Inc','Greek Life, Fraternities, & Sororities',NULL,NULL,1);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('On That Note','Art, Music, & Performance',NULL,NULL,2);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('One Love','Social Justice, Advocacy, & Activism',NULL,NULL,6);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('One Note Stand A cappella','Art, Music, & Performance','Sun Thurs','Hellems',10);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Orthodox Christian Fellowship','Religion & Spirituality',NULL,NULL,6);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('oSTEM @ the University of Colorado, Boulder','STEM','Wednesdays, 7-8 PM','In-person: BOLD Center (ECCE 100) / Virtual (link posted to Discord)',21);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('OUTLaw','Law & Law School','Alternating Mondays, 12:00 - 13:00 MST','N/A',5);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Oyate Native American and Indigenous Student Organization','Cultural and International','7:00 PM - 8:00 PM','UMC 445',9);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Painting Pals','Art, Music, & Performance','Tuesdays, 6:30 PM','Visual Arts Complex Room 475',94);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Pakistani Student Association','Cultural and International','Tuesday (6pm)','UMC/TBD',6);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Greek Life, Fraternities, & Sororities','Governing Body',NULL,NULL,4);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Phi Alpha Delta Pre-Law Fraternity','Government & Politics','5:30-6:30','Zoom: https://cuboulder.zoom.us/j/99742846893',179);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Phi Delta Theta','Greek Life, Fraternities, & Sororities',NULL,NULL,4);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Phi Kappa Sigma','Greek Life, Fraternities, & Sororities',NULL,NULL,3);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Phi Mu','Greek Life, Fraternities, & Sororities',NULL,NULL,2);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Phi Sigma Pi - Delta Sigma Chapter','Honor Society',NULL,NULL,6);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Photography Club','Art, Music, & Performance','Varies','Varies',95);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Pi Beta Phi','Greek Life, Fraternities, & Sororities',NULL,NULL,4);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Pi Delta Psi Fraternity Incorporated','Greek Life, Fraternities, & Sororities',NULL,NULL,3);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Pi Lambda Chi Latina Sorority, Inc.','Greek Life, Fraternities, & Sororities',NULL,NULL,5);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Pi Sigma Alpha','Honor Society',NULL,NULL,3);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Pickup Soccer Club','Recreation & Wellness','TBD','Kitt Field or The REC',27);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Pokemon TCG Boulder','Social',NULL,NULL,13);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Pokemon VGC','Social','Tuesday 6:30-8','CASE 224',20);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Pre-Law Student Society','Law & Law School','Wednesdays @ 5:30 pm','Wolf Law Room 411',4);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Pre-Vet Club','STEM','7:00pm','Zoom // TBA',2);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Privacy Law Society','Law & Law School',NULL,NULL,2);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Project Kind','Community Service & Volunteerism',NULL,NULL,8);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Psi Chi - CU Boulder Chapter','Honor Society',NULL,NULL,47);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Psychedelic Club','STEM',NULL,NULL,139);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Psychologists Advocating for Systemic Training in Antiracism','Social Justice, Advocacy, & Activism','12:00 pm Friday','Online (during COVID)',13);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Public Health Hub','STEM','6:30 pm every Monday','HLMS 185',8);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Public Interest Student Association','Law & Law School',NULL,NULL,4);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Public Relations Student Society of America','Humanities and Social Sciences',NULL,NULL,10);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Quad Community Council','Residence Life',NULL,NULL,3);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('REDTAC Squadron - The Composite Aircraft Build At CU','STEM','TBD','TBD',6);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Residence Hall Association','Governing Body',NULL,NULL,15);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Residence Life','Residence Life',NULL,NULL,11);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Residential Quad (Aden, Brackett, Cockrell, Crosman)','Residence Life',NULL,NULL,14);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Ritmos Latinos','Cultural and International','7:30 PM','UMC 457 - Dennis Small Cultural Center',34);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Roam Boulder','Social','7:00pm on Tuesday','Rooms 415-417 in the UMC',20);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Rocky Mountain Interdisciplinary History Conference','Humanities and Social Sciences',NULL,NULL,2);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Rocky Mountain Rescue Group CU Boulder Student Chapter','Recreation & Wellness','7:00','University of Colorado',35);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Saudi Students Association at The University of Colorado at Boulder','Cultural and International',NULL,NULL,6);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Say What!?: CU Boulder Hearing Loss Association','Social','TBD','TBD',3);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Scholars of Finance','Business & Entrepreneurship','Monday, 5-7pm','Koebel',11);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('School of Education Student Government','Governing Body',NULL,NULL,2);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Science Community Outreach Program and Education','STEM',NULL,NULL,3);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Science Under The Dome (SciDome)','STEM',NULL,NULL,18);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Sea U','Art, Music, & Performance',NULL,NULL,4);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Senior Class Council','Social',NULL,NULL,8);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Server Development','STEM',NULL,NULL,4);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Sewall Community Council','Residence Life',NULL,NULL,5);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Sewall Hall','Residence Life',NULL,NULL,11);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Shooting Sports at the University of Colorado','Recreation & Wellness',NULL,NULL,4);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Shuffle/Flow','Art, Music, & Performance',NULL,NULL,3);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Sigma Alpha Epsilon Pi','Greek Life, Fraternities, & Sororities',NULL,NULL,4);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Sigma Alpha Mu','Greek Life, Fraternities, & Sororities',NULL,NULL,3);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Sigma Chi Fraternity','Greek Life, Fraternities, & Sororities',NULL,NULL,3);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Sigma Gamma Tau','Honor Society','Monthly - exact time changes based on member availability','Aerospace Building on East Campus',5);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Sigma Lambda Beta International Fraternity Incorporated','Greek Life, Fraternities, & Sororities',NULL,NULL,4);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Sigma Lambda Gamma National Sorority Inc.','Greek Life, Fraternities, & Sororities',NULL,NULL,4);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Sigma Psi Zeta Sorority, Inc.','Greek Life, Fraternities, & Sororities',NULL,NULL,7);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Sigma Tau Gamma','Greek Life, Fraternities, & Sororities',NULL,NULL,0);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Sikh Student Association','Cultural and International','Thursdays @ 7',NULL,0);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Silicon Flatirons Student Group','Law & Law School',NULL,NULL,3);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Silver Wings','Community Service & Volunteerism',NULL,NULL,1);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('SIT HAPPENS | CU MEDITATION & THE BUDDHIST PATH','Religion & Spirituality','TBD (CHECK BACK FOR UPDATES 11/7)','TBD (CHECK BACK FOR UPDATES 11/7)',12);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('SKY Campus Happiness @ CU Boulder','Recreation & Wellness',NULL,NULL,14);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Smith & Buckingham Community Council','Residence Life',NULL,NULL,4);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Smith Hall','Residence Life',NULL,NULL,13);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Society for Industrial and Applied Mathematics Graduate Chapter','STEM',NULL,NULL,5);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Society of Asian Scientists and Engineers','STEM','Every other Tuesday from 7-8pm (starting August 30th)','The BOLD Center at the Engineering Center',5);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Society of Hispanic Professional Engineers','STEM','Wednesday 6:00PM-7:00PM (biweekly starting 9/07/22)','BOLD Center',7);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Society of Physics Students','Social','Every Wednesday at 6:00','In person',27);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Society of Women Engineers CU Boulder','STEM','6:00 - 7:00 PM every Tuesday','BOLD Center',58);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Sociology Club','Humanities and Social Sciences','Thursday 5:00pm','CASE E351',4);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Solar Decathlon','STEM','Wednesdays 6:15pm','ECCE 1B41',20);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Songwriting Club','Art, Music, & Performance','Thursday nights 5-6pm','UMC room 245',8);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('South Asian Student Association','Cultural and International','Every Thursday from 6-7 PM','ECCR 200',34);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Spaghetti Confession Improv','Art, Music, & Performance',NULL,NULL,5);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Spanish and Portuguese Graduate Association','Humanities and Social Sciences',NULL,NULL,2);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Speech and Debate Team at CU Boulder','Humanities and Social Sciences',NULL,NULL,31);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Sportsman Club','Recreation & Wellness',NULL,NULL,7);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Stearns Community Council','Residence Life',NULL,NULL,2);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Stearns East & West','Residence Life',NULL,NULL,15);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('STEM Routes','STEM',NULL,NULL,12);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('STEMinar','STEM',NULL,NULL,2);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Strategies for Ecology, Education, Diversity and Sustainability','STEM',NULL,NULL,6);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Student Affiliate Chapter of the American Society of Landscape Architects at CU Boulder','Environmental',NULL,NULL,7);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Student Bar Association','Governing Body',NULL,NULL,6);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Student Mobilization','Religion & Spirituality','7:00','TBD',1);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Student Organizations Allocations Committee','Governing Body',NULL,NULL,2);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Student Veterans Association','Social',NULL,NULL,5);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Students Against Campus Sexual Assault','Social Justice, Advocacy, & Activism',NULL,NULL,8);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Students Against Unjust Imprisonment','Social Justice, Advocacy, & Activism','6:00-7:00PM on Mondays','Zoom',14);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Students for United Campus Workers Colorado','Social Justice, Advocacy, & Activism',NULL,NULL,3);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Success Enabled Pilots','Social','Thursdays, 6:00PM-7:00PM (1800-1900) MST.','STAD 112, is subject to change',8);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Super Smash Brothers CU','Social','6:00-11:00','Flemming Hall 102',9);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Supra: A Space Force Club','STEM','6:00pm Thursdays','STAD 136C',14);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Survivor at CU Boulder','Social','Thursday @ 5:30','TBD',19);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Swap','Social Justice, Advocacy, & Activism',NULL,NULL,3);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('T9hacks','STEM','TBD','TBD',6);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Table Tennis at CU','Recreation & Wellness','Every tuesday and friday from 8pm to 10 pm','Rec Center Studio 4',55);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Taiwanese Student Association at CU Boulder','Cultural and International',NULL,NULL,22);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Tau Beta Pi','STEM','7-8pm','Engineering Center',3);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Tau Psi Omega Fraternity, Inc.','Greek Life, Fraternities, & Sororities',NULL,NULL,7);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Tau Sigma National Honor Society for Transfer Students','Honor Society',NULL,NULL,7);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Tea Club','Recreation & Wellness','N/A','NA',36);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('TEDxCU','Humanities and Social Sciences','As needed',NULL,39);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Thai Student Association','Cultural and International','TBA','TBA',13);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('The Adam Smith Society','Business & Entrepreneurship',NULL,NULL,3);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('The Annex','Religion & Spirituality','Tuesdays 8:00 PM','Grace Commons Church',4);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('The Bold Center','University Programs',NULL,NULL,9);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('The Brazen Project','Social Justice, Advocacy, & Activism',NULL,NULL,2);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('The Colorado Historian','Humanities and Social Sciences','5:30 PM every other Thursday starting on 10/6/2022','Online: https://cuboulder.zoom.us/j/5821142163, in person in Hellems 104',9);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('The Diabetes Link at CU','Social','Tuesdays at 5PM','UMC 384',5);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('The Flying Club at CU','STEM','Tuesday February 28th, 2023 6-7pm','ECCR 151',27);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('The Game of Squash Organization','Recreation & Wellness','Wedneseyday''s at 7PM','Squash Courts in the basement of the Student Recreation Center',3);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('The Herd Leadership Council','University Programs',NULL,NULL,29);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('The National Society of Collegiate Scholars','Honor Society',NULL,NULL,20);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('The National Society of Scabbard and Blade','Honor Society','Wednesdays @0700','Army ROTC Cadet Lounge',2);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('The Rocky Mountain Philosophy Conference','Humanities and Social Sciences','Thursdays 3-4pm','remote',5);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('The Society of Environmental Engineers','Environmental',NULL,NULL,26);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('The Space Law Society','Law & Law School',NULL,NULL,2);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('The Tango Club','Cultural and International','8 pm on Thursdays (class); 7:30 pm on Mondays (practice)','Studio 2 (class)/Studio 1 (practice) in the Rec Center',12);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('The Women''s Network: CU Boulder','Social','5:30 PM MT','TBD',10);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Theta Nu Xi, Multicultural Sorority, Inc.','Greek Life, Fraternities, & Sororities',NULL,NULL,0);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Theta Tau','STEM',NULL,NULL,10);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Thriving Buffs','Social',NULL,NULL,8);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Thunderchief Booster Club','Business & Entrepreneurship',NULL,NULL,4);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Track and Field Athletic Club','Recreation & Wellness',NULL,NULL,26);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Turning Point USA at the University of Colorado Boulder','Government & Politics','Every Wednesday at 7:30 PM','CASE E220',5);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('UCB Titan Productions','Art, Music, & Performance','Every Monday, 4PM - 5PM','UMC Building, Room 384',56);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('United Mexican American Students','Social Justice, Advocacy, & Activism','Every Other Thursday, 5:30-7pm','Fleming 177',16);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('University Lutheran Chapel','Religion & Spirituality',NULL,NULL,2);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('University Memorial Center','University Programs',NULL,NULL,2);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('University of Colorado Boulder Engineering Council','Governing Body',NULL,NULL,11);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('University of Colorado Boulder Running Club','Recreation & Wellness',NULL,NULL,86);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('University of Colorado Emergency Medical Services','Community Service & Volunteerism','Thursdays 6:30 pm','UMC 417/UMC 386',31);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('University of Colorado Eventing Team','Recreation & Wellness',NULL,NULL,4);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('University of Colorado Trumpet Alliance','Art, Music, & Performance','3:30 on Mondays','Imig music building',22);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('UNOS Ambassadors at CU','Community Service & Volunteerism','5:00pm-6:00pm','Zoom platform and in-person Hellems 267',16);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Vegan Justice League','Social Justice, Advocacy, & Activism','Varies','Varies',9);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('VeRVE Collisionz','Art, Music, & Performance','Wednesdays (8-10 pm) Sundays (3-5 pm)','IMIG S317',24);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Veteran''s Business Club','Business & Entrepreneurship','TBD','TBD',9);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Vietnamese Student Association','Cultural and International','Bi-Weekly Tuesday 5:30PM','CASE E240',6);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Volunteers Around the World CU Boulder Chapter','Community Service & Volunteerism','Mondays @ 5 pm','Join VAW 2021-2022 GroupMe for weekly location',8);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Warhammer Buffs','Social',NULL,NULL,27);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Willard & Reed Hall','Residence Life',NULL,NULL,19);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Williams Village East','Residence Life',NULL,NULL,21);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Williams Village East Community Council','Residence Life',NULL,NULL,3);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Williams Village North','Residence Life',NULL,NULL,12);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Williams Village North Community Council','Residence Life',NULL,NULL,4);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Women in Business','Business & Entrepreneurship','Wednesdays 6:30pm','KOBL 101',118);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Women in Construction','STEM','Monday 8PM-9PM','ECCR 108',7);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Women in Cybersecurity (WiCyS - CU Boulder Chapter)','STEM','Last Friday of Every Month','Zoom',5);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Women in Economics','Business & Entrepreneurship',NULL,NULL,2);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Women in Finance','Business & Entrepreneurship',NULL,NULL,23);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Women in Philosophy','Humanities and Social Sciences','Thursdays at 6:00pm','HLMS 251',13);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Women of Aeronautics and Astronautics','STEM','7:00 PM','Bold Center',29);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Women of Color Collective','Law & Law School',NULL,NULL,4);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Women of Color in STEM','STEM','5:30 PM - 6:30 PM every other Thursday','On Campus TBD',14);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Women''s Club Soccer','Recreation & Wellness',NULL,NULL,20);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Women''s Law Caucus','Law & Law School',NULL,NULL,10);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Yoga for Creativity','Recreation & Wellness','12:30 - 1 p.m. every Tuesday','Imig Music Building',105);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Young Democratic Socialists of America','Social Justice, Advocacy, & Activism',NULL,NULL,42);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Young Life College','Social','Wednesday, 7-9pm','Varies!',28);
INSERT INTO clubs(club_name,category,meeting_time,location,members) VALUES ('Yu-Gi-Oh Club','Social','6-9 pm','Ketchum',6);


INSERT INTO categories (category_name) VALUES ('Humanities and Social Sciences');
INSERT INTO categories (category_name) VALUES ('STEM');
INSERT INTO categories (category_name) VALUES ('Art, Music, & Performance');
INSERT INTO categories (category_name) VALUES ('Business & Entrepreneurship');
INSERT INTO categories (category_name) VALUES ('Community Service & Volunteerism');
INSERT INTO categories (category_name) VALUES ('Greek Life, Fraternities, & Sororities');
INSERT INTO categories (category_name) VALUES ('Cultural and International');
INSERT INTO categories (category_name) VALUES ('University Programs');
INSERT INTO categories (category_name) VALUES ('Environmental');
INSERT INTO categories (category_name) VALUES ('Governing Body');
INSERT INTO categories (category_name) VALUES ('Government & Politics');
INSERT INTO categories (category_name) VALUES ('Graduate and Professional Studies');
INSERT INTO categories (category_name) VALUES ('Honor Society');
INSERT INTO categories (category_name) VALUES ('Law & Law School');
INSERT INTO categories (category_name) VALUES ('Recreation & Wellness');
INSERT INTO categories (category_name) VALUES ('Religion & Spirituality');
INSERT INTO categories (category_name) VALUES ('Residence Life');
INSERT INTO categories (category_name) VALUES ('Social');
INSERT INTO categories (category_name) VALUES ('Social Justice, Advocacy, & Activism');


INSERT INTO users_clubs (username, club_id) VALUES ('vilo2343', 10);
